/**
 * Tenant-configurable role-profile CRUD — GET/POST/PUT/DELETE /api/role-profiles.
 *
 * Route idiom copied from: server/api/contractor-types.ts (createApiRouter +
 * withMcpMetadata) and server/api/email-templates.ts (admin-gated settings
 * resource, x-scopes: ['admin']).
 *
 * System profiles (isSystem:true, seeded by seedRoleProfiles) can be edited
 * (label/templates) but never deactivated or deleted — PeopleService throws
 * Errors.Conflict, mapped to 409 by the global onError handler.
 */
import { createRoute, z } from '@hono/zod-openapi';
import { createApiRouter } from '../lib/openapi-router';
import { requireRole } from '../lib/middleware/rbac';
import { withMcpMetadata } from '../lib/route-metadata-standards';
import { CreateRoleProfileSchema, UpdateRoleProfileSchema, RoleProfileSchema } from '../lib/validations/role-profile.schema';
import { auditFromContext } from '../lib/audit';

const RoleProfileListResponseSchema = z.object({
    success: z.literal(true),
    data: z.array(RoleProfileSchema),
});

const RoleProfileResponseSchema = z.object({
    success: z.literal(true),
    data: RoleProfileSchema,
});

const IdParamSchema = z.object({
    id: z.string().min(1).describe('Role profile id.'),
});

// ─── GET /role-profiles ─────────────────────────────────────────────────────
const listRoute = createRoute(withMcpMetadata({
    method: 'get',
    path: '/',
    tags: ['role-profiles'],
    summary: 'List role profiles for the current tenant',
    middleware: [requireRole('owner', 'manager', 'inspector')],
    request: {},
    responses: {
        200: { content: { 'application/json': { schema: RoleProfileListResponseSchema } }, description: 'Active and inactive role profiles, sorted for display' },
    },
    operationId: 'listRoleProfiles',
    description: 'Returns every role profile (both active and inactive) for the current tenant, ordered by sortOrder for display in the settings UI.',
}, { scopes: ['admin'], tier: 'extended' }));

// ─── POST /role-profiles ────────────────────────────────────────────────────
const createRoute_ = createRoute(withMcpMetadata({
    method: 'post',
    path: '/',
    tags: ['role-profiles'],
    summary: 'Create a tenant-defined role profile',
    middleware: [requireRole('owner', 'manager')],
    request: { body: { content: { 'application/json': { schema: CreateRoleProfileSchema } } } },
    responses: {
        201: { content: { 'application/json': { schema: RoleProfileResponseSchema } }, description: 'Role profile created' },
    },
    operationId: 'createRoleProfile',
    description: 'Creates a new tenant-defined role profile (isSystem:false) with a machine key auto-generated by slugifying the label, disambiguated for uniqueness.',
}, { scopes: ['admin'], tier: 'extended' }));

// ─── PUT /role-profiles/:id ──────────────────────────────────────────────────
const updateRoute = createRoute(withMcpMetadata({
    method: 'put',
    path: '/{id}',
    tags: ['role-profiles'],
    summary: 'Update a role profile for the current tenant',
    middleware: [requireRole('owner', 'manager')],
    request: {
        params: IdParamSchema,
        body: { content: { 'application/json': { schema: UpdateRoleProfileSchema } } },
    },
    responses: {
        200: { content: { 'application/json': { schema: z.object({ success: z.literal(true), data: z.object({ updated: z.literal(true) }) }) } }, description: 'Role profile updated' },
        404: { content: { 'application/json': { schema: z.object({ success: z.literal(false), error: z.object({ message: z.string(), code: z.string() }) }) } }, description: 'Role profile not found' },
        409: { content: { 'application/json': { schema: z.object({ success: z.literal(false), error: z.object({ message: z.string(), code: z.string() }) }) } }, description: 'System role profiles cannot be deactivated' },
    },
    operationId: 'updateRoleProfile',
    description: 'Updates the label, email/SMS template links, or active flag of a role profile. Key and kind are immutable. System profiles reject active:false with a 409 conflict.',
}, { scopes: ['admin'], tier: 'extended' }));

// ─── DELETE /role-profiles/:id ───────────────────────────────────────────────
const deleteRoute = createRoute(withMcpMetadata({
    method: 'delete',
    path: '/{id}',
    tags: ['role-profiles'],
    summary: 'Soft-delete a role profile for the current tenant',
    middleware: [requireRole('owner', 'manager')],
    request: { params: IdParamSchema },
    responses: {
        200: { content: { 'application/json': { schema: z.object({ success: z.literal(true), data: z.object({ deactivated: z.literal(true) }) }) } }, description: 'Role profile deactivated' },
        404: { content: { 'application/json': { schema: z.object({ success: z.literal(false), error: z.object({ message: z.string(), code: z.string() }) }) } }, description: 'Role profile not found' },
        409: { content: { 'application/json': { schema: z.object({ success: z.literal(false), error: z.object({ message: z.string(), code: z.string() }) }) } }, description: 'System role profiles cannot be deleted' },
    },
    operationId: 'deleteRoleProfile',
    description: 'Soft-deletes a role profile by setting active:false. System profiles (isSystem:true) are protected and respond with a 409 conflict instead.',
}, { scopes: ['admin'], tier: 'extended' }));

const roleProfilesRoutes = createApiRouter()
    .openapi(listRoute, async (c) => {
        const tenantId = c.get('tenantId');
        const data = await c.var.services.people.listProfiles(tenantId);
        return c.json({ success: true as const, data }, 200);
    })
    .openapi(createRoute_, async (c) => {
        const tenantId = c.get('tenantId');
        const input = c.req.valid('json');
        const data = await c.var.services.people.createProfile(tenantId, input);
        return c.json({ success: true as const, data }, 201);
    })
    .openapi(updateRoute, async (c) => {
        const tenantId = c.get('tenantId');
        const { id } = c.req.valid('param');
        const patch = c.req.valid('json');
        const { capabilityDiff } = await c.var.services.people.updateProfile(tenantId, id, patch);
        // Role-profile edits are permission-bearing now, so they join the audit
        // trail staff permission_overrides changes already have — before/after
        // resolved sets, not just "role updated".
        if (capabilityDiff) {
            auditFromContext(c, 'role_profile.capabilities_updated', 'contact_role_profile', {
                entityId: id,
                metadata: capabilityDiff,
            });
        }
        return c.json({ success: true as const, data: { updated: true as const } }, 200);
    })
    .openapi(deleteRoute, async (c) => {
        const tenantId = c.get('tenantId');
        const { id } = c.req.valid('param');
        await c.var.services.people.deactivateProfile(tenantId, id);
        return c.json({ success: true as const, data: { deactivated: true as const } }, 200);
    });

export type RoleProfilesApi = typeof roleProfilesRoutes;

export default roleProfilesRoutes;
