// Spec 4A — TOTP 2FA sub-router.
//
// Behavior-preserving extraction from auth.ts — handler bodies + route
// definitions are byte-identical to the original (only their location changed).
// These five endpoints (2FA enroll/verify/disable, recovery-code regenerate,
// and the second-factor login exchange) are additive and were always grouped
// together. JWT signing/verification still flows through the keyring; cookie
// attributes come from the shared `authCookieOptions` helper.
import { createRoute } from '@hono/zod-openapi';
import type { Context } from 'hono';
import { createApiRouter } from '../../lib/openapi-router';
import type { HonoConfig } from '../../types/hono';
import { and, eq, isNull } from 'drizzle-orm';
import { users } from '../../lib/db/schema';
import { setCookie } from 'hono/cookie';
import { Errors } from '../../lib/errors';
import { checkRateLimit } from '../../lib/rate-limit';
import { requireCsrfToken } from '../../lib/middleware/csrf';
import { verifyPassword } from '../../lib/password';
import { signJwt, verifyJwt } from '../../lib/jwt-keyring';
import {
    TotpVerifySchema,
    TotpDisableSchema,
    TotpLoginSchema,
    TotpSetupResponseSchema,
    Login2faResponseSchema
} from '../../lib/validations/auth.schema';
import { SuccessResponseSchema } from '../../lib/validations/shared.schema';
import { withMcpMetadata } from '../../lib/route-metadata-standards';
import { authCookieOptions, AUTH_COOKIE_NAME } from '../../lib/auth-helpers';
import { getDrizzle } from '../../lib/route-helpers';

// ─── Spec 4A — TOTP 2FA endpoints ──────────────────────────────────────────
// All 5 endpoints below were added by Spec 4A. They are additive — no existing
// behaviour was altered beyond the requires2fa branch in the login handler above.

const TOTP_ISSUER = 'OpenInspection';

/** Look up the current user row or 401 if the JWT is missing/stale. */
async function loadCurrentUser(c: Context<HonoConfig>) {
    const userPayload = c.get('user');
    if (!userPayload?.sub) throw Errors.Unauthorized();
    const db = getDrizzle(c);
    const row = await db.select().from(users).where(eq(users.id, userPayload.sub)).get();
    if (!row) throw Errors.Unauthorized();
    return row;
}

const totpSetupRoute = createRoute(withMcpMetadata({
    method: 'post',
    path: '/2fa/setup',
    operationId: 'beginTotpEnrollment',
    summary: 'Begin TOTP 2FA enrollment',
    description: 'Generates a fresh TOTP secret plus recovery codes and returns the QR data URI. Caller must POST /2fa/verify before 2FA is actually enabled.',
    tags: ['auth'],
    responses: {
        200: { content: { 'application/json': { schema: TotpSetupResponseSchema.describe('TODO describe schema field for the OpenInspection MCP integration') } }, description: 'Setup payload' },
        401: { description: 'Unauthorized' },
    }
}, { scopes: [], tier: 'extended' }));

const totpVerifyRoute = createRoute(withMcpMetadata({
    method: 'post',
    path: '/2fa/verify',
    operationId: 'activateTotp',
    summary: 'Activate TOTP two-factor authentication',
    description: 'Verifies the supplied TOTP code against the pending secret generated by /2fa/setup. On success, flips totpEnabled to true on the user record.',
    tags: ['auth'],
    request: { body: { content: { 'application/json': { schema: TotpVerifySchema.describe('TODO describe schema field for the OpenInspection MCP integration') } } } },
    responses: {
        200: { content: { 'application/json': { schema: SuccessResponseSchema.describe('TODO describe schema field for the OpenInspection MCP integration') } }, description: '2FA enabled' },
        400: { description: 'Invalid code or no pending secret' },
        401: { description: 'Unauthorized' },
    }
}, { scopes: [], tier: 'extended' }));

const totpDisableRoute = createRoute(withMcpMetadata({
    method: 'post',
    path: '/2fa/disable',
    operationId: 'disableTotp',
    summary: 'Disable TOTP two-factor authentication',
    description: 'Requires both the current password and a valid TOTP or recovery code to disable 2FA. Wipes all 2FA state (secret, enabled flag, recovery codes).',
    tags: ['auth'],
    request: { body: { content: { 'application/json': { schema: TotpDisableSchema.describe('TODO describe schema field for the OpenInspection MCP integration') } } } },
    responses: {
        200: { content: { 'application/json': { schema: SuccessResponseSchema.describe('TODO describe schema field for the OpenInspection MCP integration') } }, description: '2FA disabled' },
        400: { description: 'Invalid input' },
        401: { description: 'Unauthorized — wrong password or code' },
    }
}, { scopes: [], tier: 'extended' }));

const totpRegenRoute = createRoute(withMcpMetadata({
    method: 'post',
    path: '/2fa/recovery-codes/regenerate',
    operationId: 'regenerateTotpRecoveryCodes',
    summary: 'Regenerate 2FA recovery codes',
    description: 'Invalidates all existing 2FA recovery codes and returns a fresh set of eight. Requires the current password plus a valid TOTP or recovery code.',
    tags: ['auth'],
    request: { body: { content: { 'application/json': { schema: TotpDisableSchema.describe('TODO describe schema field for the OpenInspection MCP integration') } } } },
    responses: {
        200: { content: { 'application/json': { schema: TotpSetupResponseSchema.describe('TODO describe schema field for the OpenInspection MCP integration') } }, description: 'New recovery codes' },
        401: { description: 'Unauthorized' },
    }
}, { scopes: [], tier: 'extended' }));

const login2faRoute = createRoute(withMcpMetadata({
    method: 'post',
    path: '/login/2fa',
    operationId: 'completeTwoFactorLogin',
    summary: 'Complete two-factor authentication login',
    description: 'Exchanges a short-lived 2FA challenge token plus TOTP or recovery code for a full session cookie. The challenge token is issued by /login when 2FA is enabled.',
    tags: ['auth', 'public'],
    middleware: [requireCsrfToken],
    request: { body: { content: { 'application/json': { schema: TotpLoginSchema.describe('TODO describe schema field for the OpenInspection MCP integration') } } } },
    responses: {
        200: { content: { 'application/json': { schema: Login2faResponseSchema.describe('TODO describe schema field for the OpenInspection MCP integration') } }, description: 'Login complete' },
        401: { description: 'Invalid or expired challenge / code' },
    }
}, { scopes: [], tier: 'excluded' }));

const totpRoutes = createApiRouter()
    .openapi(totpSetupRoute, async (c) => {
        const me = await loadCurrentUser(c);
        // Setup overwrites the secret and clears totpEnabled until /2fa/verify
        // proves the new one. On an account that already has a second factor
        // that is a disable — and /2fa/disable demands password + code for it.
        // A session alone must not be able to strip the second factor.
        if (me.totpEnabled) {
            throw Errors.Conflict('Two-factor authentication is already enabled. Disable it first.');
        }
        const totpSvc = c.var.services.totp;

        const secret = totpSvc.generateSecret();
        const recoveryCodes = totpSvc.generateRecoveryCodes(8);
        const recoveryHashes = await Promise.all(recoveryCodes.map(rc => totpSvc.hashCode(rc)));
        const otpAuthUrl = totpSvc.buildOtpAuthUrl({ accountName: me.email, issuer: TOTP_ISSUER, secret });
        const qrCodeDataUri = await totpSvc.qrCodeDataUri(otpAuthUrl);

        // Persist the secret + recovery hashes immediately, but keep totpEnabled=false until
        // the user proves they can produce a valid code via /2fa/verify. This way an abandoned
        // setup never locks anyone out.
        const db = getDrizzle(c);
        await db.update(users).set({
            totpSecret: secret,
            totpRecoveryCodes: JSON.stringify(recoveryHashes),
            totpEnabled: false,
            totpVerifiedAt: null,
        }).where(eq(users.id, me.id));

        return c.json({
            success: true,
            data: { secret, qrCodeDataUri, recoveryCodes }
        }, 200);
    })
    .openapi(totpVerifyRoute, async (c) => {
        await checkRateLimit(c, 'totp');
        // A 6-digit code is a 1e6 space; without this an attacker holding a
        // session and password brute-forces the second factor at full speed.
        const me = await loadCurrentUser(c);
        if (!me.totpSecret) throw Errors.BadRequest('No pending 2FA setup. Call /2fa/setup first.');

        const { code } = c.req.valid('json');
        const ok = c.var.services.totp.verifyCode(me.totpSecret, code);
        if (!ok) throw Errors.BadRequest('Invalid verification code');

        const db = getDrizzle(c);
        await db.update(users).set({
            totpEnabled: true,
            totpVerifiedAt: new Date(),
        }).where(eq(users.id, me.id));

        return c.json({ success: true }, 200);
    })
    .openapi(totpDisableRoute, async (c) => {
        await checkRateLimit(c, 'totp');
        // A 6-digit code is a 1e6 space; without this an attacker holding a
        // session and password brute-forces the second factor at full speed.
        const me = await loadCurrentUser(c);
        const { password, code } = c.req.valid('json');

        const [pwOk] = await verifyPassword(password, me.passwordHash);
        if (!pwOk) throw Errors.Unauthorized('Invalid credentials');

        if (!me.totpEnabled || !me.totpSecret) throw Errors.BadRequest('2FA is not enabled');

        const totpSvc = c.var.services.totp;
        let codeOk = totpSvc.verifyCode(me.totpSecret, code);
        let updatedHashes: string[] | null = null;
        if (!codeOk && me.totpRecoveryCodes) {
            const hashes = JSON.parse(me.totpRecoveryCodes) as string[];
            const result = await totpSvc.consumeRecoveryCode(code, hashes);
            codeOk = result.matched;
            if (result.matched) updatedHashes = result.remainingHashes;
        }
        if (!codeOk) throw Errors.Unauthorized('Invalid verification code');

        const db = getDrizzle(c);
        await db.update(users).set({
            totpSecret: null,
            totpEnabled: false,
            totpRecoveryCodes: null,
            totpVerifiedAt: null,
        }).where(eq(users.id, me.id));

        // updatedHashes intentionally discarded — we are wiping all 2FA state anyway.
        void updatedHashes;
        return c.json({ success: true }, 200);
    })
    .openapi(totpRegenRoute, async (c) => {
        await checkRateLimit(c, 'totp');
        // A 6-digit code is a 1e6 space; without this an attacker holding a
        // session and password brute-forces the second factor at full speed.
        const me = await loadCurrentUser(c);
        const { password, code } = c.req.valid('json');

        const [pwOk] = await verifyPassword(password, me.passwordHash);
        if (!pwOk) throw Errors.Unauthorized('Invalid credentials');

        if (!me.totpEnabled || !me.totpSecret) throw Errors.BadRequest('2FA is not enabled');

        const totpSvc = c.var.services.totp;
        let codeOk = totpSvc.verifyCode(me.totpSecret, code);
        if (!codeOk && me.totpRecoveryCodes) {
            const hashes = JSON.parse(me.totpRecoveryCodes) as string[];
            const result = await totpSvc.consumeRecoveryCode(code, hashes);
            codeOk = result.matched;
            // We are about to overwrite recovery codes wholesale, so consuming the matched code
            // here doesn't need to be persisted separately.
        }
        if (!codeOk) throw Errors.Unauthorized('Invalid verification code');

        const recoveryCodes = totpSvc.generateRecoveryCodes(8);
        const recoveryHashes = await Promise.all(recoveryCodes.map(rc => totpSvc.hashCode(rc)));

        const db = getDrizzle(c);
        await db.update(users).set({
            totpRecoveryCodes: JSON.stringify(recoveryHashes),
        }).where(eq(users.id, me.id));

        // QR code is irrelevant on regenerate; surface an empty string to keep the schema stable.
        return c.json({
            success: true,
            data: { secret: me.totpSecret, qrCodeDataUri: '', recoveryCodes }
        }, 200);
    })
    .openapi(login2faRoute, async (c) => {
        await checkRateLimit(c, 'login');

        const { challengeToken, code } = c.req.valid('json');
        const keyring = await c.var.keyringPromise!;

        let payload: Record<string, unknown>;
        try {
            payload = await verifyJwt(challengeToken, keyring);
        } catch {
            throw Errors.Unauthorized('Invalid or expired challenge');
        }
        if (payload['t'] !== 'challenge' || typeof payload['sub'] !== 'string') {
            throw Errors.Unauthorized('Invalid challenge token');
        }
        const userId = payload['sub'] as string;

        const db = getDrizzle(c);
        // Excludes soft-deleted (removed member) rows — this is the second
        // half of the login flow, so it must honor the same active-user gate
        // as validateCredentials.
        const me = await db.select().from(users).where(and(eq(users.id, userId), isNull(users.deletedAt))).get();
        if (!me || !me.totpEnabled || !me.totpSecret) {
            throw Errors.Unauthorized('Invalid challenge token');
        }

        const totpSvc = c.var.services.totp;
        let codeOk = totpSvc.verifyCode(me.totpSecret, code);
        if (!codeOk && me.totpRecoveryCodes) {
            const hashes = JSON.parse(me.totpRecoveryCodes) as string[];
            const result = await totpSvc.consumeRecoveryCode(code, hashes);
            if (result.matched) {
                codeOk = true;
                // Single-use semantics: persist remaining hashes immediately, before we issue
                // the session cookie. If the DB write fails we don't want to grant a session.
                await db.update(users).set({
                    totpRecoveryCodes: JSON.stringify(result.remainingHashes),
                }).where(eq(users.id, me.id));
            }
        }
        if (!codeOk) throw Errors.Unauthorized('Invalid verification code');

        const now = Math.floor(Date.now() / 1000);
        const sessionToken = await signJwt({
            sub: me.id,
            'custom:tenantId': me.tenantId,
            'custom:userRole': me.role,
            role: me.role,
            iat: now,
            exp: now + 60 * 60 * 24,
        }, keyring);

        setCookie(c, AUTH_COOKIE_NAME, sessionToken, authCookieOptions());
        return c.json({ success: true, data: { redirect: '/inspections' } }, 200);
    });

export default totpRoutes;
