import { CONTACT_BITS, capabilitiesForProfile, type RoleCapabilities } from "../../../server/lib/people/capabilities";
import { m } from "~/paraglide/messages";
import type { RoleProfile } from "./contacts-helpers";

/**
 * The `?` capability matrix on the Roles page — roles down one axis,
 * capabilities across the other, GENERATED by iterating CONTACT_BITS so a new
 * bit cannot leave this reference silently stale (a missing label falls back
 * to the key, which is ugly enough to get fixed). Five booleans with no
 * explanation is how email_template_id became IA-93: configured in good faith,
 * understood by nobody.
 */

const CAP_LABEL: Record<string, () => string> = {
  receivesReport: () => m.contacts_roles_modal_cap_receives_report(),
  selfRetrieveReport: () => m.contacts_roles_modal_cap_self_retrieve(),
  canHaveAccount: () => m.contacts_roles_modal_cap_can_have_account(),
  showsInAgentPortal: () => m.contacts_roles_modal_cap_shows_in_agent_portal(),
  canAccessRepairList: () => m.contacts_roles_modal_cap_repair_list_label(),
};

const CAP_DESC: Record<string, () => string> = {
  receivesReport: () => m.contacts_roles_matrix_desc_receivesReport(),
  selfRetrieveReport: () => m.contacts_roles_matrix_desc_selfRetrieveReport(),
  canHaveAccount: () => m.contacts_roles_matrix_desc_canHaveAccount(),
  showsInAgentPortal: () => m.contacts_roles_matrix_desc_showsInAgentPortal(),
  canAccessRepairList: () => m.contacts_roles_matrix_desc_canAccessRepairList(),
};

const REPAIR_LABEL: Record<string, () => string> = {
  off: () => m.contacts_roles_modal_cap_repair_off(),
  read: () => m.contacts_roles_modal_cap_repair_read(),
  readwrite: () => m.contacts_roles_modal_cap_repair_readwrite(),
};

function cellValue(caps: RoleCapabilities, key: string): string {
  const v = caps[key as keyof RoleCapabilities];
  if (typeof v === "boolean") return v ? "✓" : "—";
  return REPAIR_LABEL[String(v)]?.() ?? String(v);
}

export function CapabilityMatrix({ roles }: { roles: RoleProfile[] }) {
  const capKeys = Object.keys(CONTACT_BITS);
  const active = roles.filter((r) => r.active);
  return (
    <div className="space-y-3 max-w-[520px]">
      <h3 className="text-sm font-semibold text-ih-fg-1">{m.contacts_roles_matrix_title()}</h3>
      <div className="overflow-x-auto">
        <table className="text-xs w-full">
          <thead>
            <tr>
              <th className="text-left font-semibold text-ih-fg-3 pr-2 pb-1" />
              {capKeys.map((key) => (
                <th key={key} data-capability={key} scope="col"
                    className="text-left font-semibold text-ih-fg-3 px-2 pb-1 align-bottom">
                  {CAP_LABEL[key]?.() ?? key}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {active.map((role) => {
              const caps = capabilitiesForProfile(role.kind, role.capabilityOverrides ?? null);
              return (
                <tr key={role.id} className="border-t border-ih-border">
                  <th scope="row" className="text-left font-medium text-ih-fg-1 pr-2 py-1 whitespace-nowrap">{role.label}</th>
                  {capKeys.map((key) => (
                    <td key={key} className="px-2 py-1 text-ih-fg-2">{cellValue(caps, key)}</td>
                  ))}
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
      <ul className="space-y-1 text-xs text-ih-fg-3">
        {capKeys.map((key) => (
          <li key={key}>
            <span className="font-medium text-ih-fg-2">{CAP_LABEL[key]?.() ?? key}</span>
            {" — "}
            {CAP_DESC[key]?.() ?? key}
          </li>
        ))}
      </ul>
    </div>
  );
}
