import { useLoaderData } from "react-router";
import type { Route } from "./+types/legal";
import { createApi } from "~/lib/api-client.server";
import { m } from "~/paraglide/messages";

export function meta({ loaderData }: Route.MetaArgs) {
  const data = loaderData as typeof loaderData | undefined;
  if (!data) return [{ title: m.public_legal_meta_default() }];
  const docTitle = data.doc === "privacy" ? m.public_legal_doc_privacy() : m.public_legal_doc_terms();
  return [{ title: m.public_legal_title({ doc: docTitle, company: data.companyName }) }];
}

const ALLOWED_DOCS = ["privacy", "terms"] as const;
type LegalDoc = (typeof ALLOWED_DOCS)[number];

function isAllowedDoc(v: string): v is LegalDoc {
  return (ALLOWED_DOCS as readonly string[]).includes(v);
}

export const SMS_CLAUSE_HEADING = "SMS & Text Messaging";
export const SMS_CLAUSE_TEXT =
  "If you provide a mobile number and opt in, {{company}} may send you appointment reminders, " +
  "report-ready notifications, and other transactional messages about your inspection by text. " +
  "Message frequency varies by your inspection activity. Message and data rates may apply. " +
  "Reply STOP to opt out and HELP for help. " +
  "Consent is not a condition of any purchase. " +
  "We do not sell or share mobile opt-in information or your phone number with third parties " +
  "or affiliates for their marketing. SMS is delivered through our provider, Twilio, Inc.";

export function mergeCompany(template: string, company: string | null): string {
  return template.replace(/\{\{company\}\}/g, company ?? "[Your Company]");
}

const MONTHS = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
];

/**
 * `2026-08-01` -> `August 1, 2026`.
 *
 * Deliberately string arithmetic and no `Date` anywhere. The input is already a
 * civil date computed in the TENANT's timezone; handing it to `new Date()` here
 * would re-interpret it as a UTC instant and then read local parts back off it,
 * which is how a date renders as the day before for every reader west of
 * Greenwich. There is no instant in this value to lose.
 */
export function formatLegalVersion(version: string | null): string | null {
  if (!version) return null;
  const m = /^(\d{4})-(\d{2})-(\d{2})$/.exec(version);
  if (!m) return version;
  const month = MONTHS[Number(m[2]) - 1];
  if (!month) return version;
  return `${month} ${Number(m[3])}, ${m[1]}`;
}

export async function loader({ params, context }: Route.LoaderArgs) {
  const { tenant, doc } = params;

  if (!doc || !isAllowedDoc(doc) || !tenant) {
    throw new Response(null, { status: 404 });
  }

  const api = createApi(context);
  const res = await api.publicReport.legal[":tenant"][":doc"].$get({
    param: { tenant, doc },
  });
  if (!res.ok) {
    throw new Response(null, { status: 404 });
  }
  const body = (await res.json()) as {
    data?: { companyName?: string; body?: string | null; lastUpdated?: string | null };
  };
  const companyName = body.data?.companyName?.trim();
  if (!companyName) {
    throw new Response(null, { status: 404 });
  }

  return {
    doc,
    companyName,
    customBody: body.data?.body?.trim() || null,
    lastUpdated: body.data?.lastUpdated ?? null,
    tenantSlug: tenant,
  };
}

function PrivacyContent({ company }: { company: string }) {
  const smsText = mergeCompany(SMS_CLAUSE_TEXT, company);
  return (
    <>
      <section>
        <h2 className="text-lg font-semibold text-ih-fg-1 mb-2">
          1. Information We Collect
        </h2>
        <p className="text-[15px] text-ih-fg-2 leading-relaxed">
          When you book an inspection or use our services, we collect information you
          provide directly — such as your name, email address, phone number, and
          property address — as well as information generated by your use of the
          platform (inspection records, communications, uploaded photos and documents).
        </p>
      </section>

      <section>
        <h2 className="text-lg font-semibold text-ih-fg-1 mb-2">
          2. How We Use Your Information
        </h2>
        <p className="text-[15px] text-ih-fg-2 leading-relaxed">
          We use your information to schedule and deliver inspection services,
          communicate with you about your inspection, generate and share your
          inspection report, process payments, and comply with legal obligations.
          We do not sell your personal information to third parties.
        </p>
      </section>

      <section>
        <h2 className="text-lg font-semibold text-ih-fg-1 mb-2">
          3. Sharing of Information
        </h2>
        <p className="text-[15px] text-ih-fg-2 leading-relaxed">
          We share your information only with your inspection company, its agents,
          and the service providers they use to deliver inspection services (such as
          email delivery, payment processing, and document storage). We do not share
          your information with unrelated third parties for their own marketing
          purposes.
        </p>
      </section>

      <section>
        <h2 className="text-lg font-semibold text-ih-fg-1 mb-2">
          4. {SMS_CLAUSE_HEADING}
        </h2>
        <p className="text-[15px] text-ih-fg-2 leading-relaxed">
          {smsText}
        </p>
      </section>

      <section>
        <h2 className="text-lg font-semibold text-ih-fg-1 mb-2">
          5. Data Retention
        </h2>
        <p className="text-[15px] text-ih-fg-2 leading-relaxed">
          We retain your personal information for as long as necessary to deliver
          inspection services and comply with applicable laws. You may request
          deletion of your data by contacting your inspection company.
        </p>
      </section>

      <section>
        <h2 className="text-lg font-semibold text-ih-fg-1 mb-2">
          6. Contact
        </h2>
        <p className="text-[15px] text-ih-fg-2 leading-relaxed">
          Questions about this Privacy Policy? Contact {company} directly through
          the booking or contact information provided by your inspector.
        </p>
      </section>
    </>
  );
}

function TermsContent({ company }: { company: string }) {
  return (
    <>
      <section>
        <h2 className="text-lg font-semibold text-ih-fg-1 mb-2">
          1. Acceptance
        </h2>
        <p className="text-[15px] text-ih-fg-2 leading-relaxed">
          By booking an inspection or using the services provided by {company},
          you agree to these Terms of Service. If you do not agree, do not use
          the services.
        </p>
      </section>

      <section>
        <h2 className="text-lg font-semibold text-ih-fg-1 mb-2">
          2. Services
        </h2>
        <p className="text-[15px] text-ih-fg-2 leading-relaxed">
          {company} provides property inspection services including scheduling,
          on-site inspection, and digital report delivery. The scope of each
          inspection is described at booking and in the pre-inspection agreement.
        </p>
      </section>

      <section>
        <h2 className="text-lg font-semibold text-ih-fg-1 mb-2">
          3. Payment
        </h2>
        <p className="text-[15px] text-ih-fg-2 leading-relaxed">
          Payment is due as specified at booking. You authorize {company} to charge
          the agreed amount using the payment method you provide. All fees are
          non-refundable unless otherwise stated.
        </p>
      </section>

      <section>
        <h2 className="text-lg font-semibold text-ih-fg-1 mb-2">
          4. Text Messaging (SMS)
        </h2>
        <p className="text-[15px] text-ih-fg-2 mb-2 leading-relaxed font-medium">
          a. Your consent.
        </p>
        <p className="text-[15px] text-ih-fg-2 leading-relaxed mb-3">
          If you opt into text messages, {company} will send you appointment
          reminders, report-ready notifications, and other transactional messages
          about your inspection. Message and data rates may apply. Message frequency
          varies by your inspection activity.
        </p>
        <p className="text-[15px] text-ih-fg-2 mb-2 leading-relaxed font-medium">
          b. Opt-out.
        </p>
        <p className="text-[15px] text-ih-fg-2 leading-relaxed mb-3">
          Reply STOP at any time to stop receiving messages, or HELP for help.
          Consent is not a condition of booking. We do not sell, share, rent, or
          transfer your mobile opt-in information or phone number to third parties
          or affiliates for their marketing. Opt-in is specific to {company} and
          is not shared across businesses or use cases.
        </p>
        <p className="text-[15px] text-ih-fg-2 mb-2 leading-relaxed font-medium">
          c. Provider.
        </p>
        <p className="text-[15px] text-ih-fg-2 leading-relaxed">
          SMS is delivered through our provider, Twilio, Inc. Your use of
          messaging is subject to Twilio&apos;s Acceptable Use Policy and Messaging
          Policy. Carriers are not liable for delayed or undelivered messages.
        </p>
      </section>

      <section>
        <h2 className="text-lg font-semibold text-ih-fg-1 mb-2">
          5. Limitation of Liability
        </h2>
        <p className="text-[15px] text-ih-fg-2 leading-relaxed">
          To the fullest extent permitted by law, {company} and its inspectors
          shall not be liable for indirect, incidental, or consequential damages.
          Liability is limited to the fee paid for the inspection.
        </p>
      </section>

      <section>
        <h2 className="text-lg font-semibold text-ih-fg-1 mb-2">
          6. Contact
        </h2>
        <p className="text-[15px] text-ih-fg-2 leading-relaxed">
          Questions about these Terms? Contact {company} directly through the
          booking or contact information provided by your inspector.
        </p>
      </section>
    </>
  );
}

export default function LegalPage() {
  const { doc, companyName, customBody, lastUpdated } = useLoaderData<typeof loader>();

  const isPrivacy = doc === "privacy";
  const docTitle = isPrivacy ? m.public_legal_doc_privacy() : m.public_legal_doc_terms();
  const heading = m.public_legal_title({ doc: docTitle, company: companyName });
  // Was a hardcoded literal — one date, baked into the message catalogue, shown
  // on EVERY tenant's page whatever their document said or when they last
  // touched it, and stale the moment the release shipped. It now comes from the
  // version registry, which is the only thing that knows a save changed the
  // TEXT rather than some neighbouring setting. Null until a tenant has
  // published once, and then the line is omitted rather than invented.
  const effectiveDate = formatLegalVersion(lastUpdated);

  return (
    <div className="min-h-screen bg-ih-bg-card text-ih-fg-1 py-12 px-4">
      <main className="max-w-[720px] mx-auto">
        <header className="mb-8">
          <p className="text-xs font-medium text-ih-fg-3 uppercase tracking-widest mb-3">
            {companyName}
          </p>
          <h1 className="font-serif text-3xl font-bold text-ih-fg-1 leading-tight mb-2">
            {heading}
          </h1>
          {effectiveDate && (
            <p className="text-sm text-ih-fg-3">
              {m.public_legal_last_updated({ date: effectiveDate })}
            </p>
          )}
        </header>

        <div className="space-y-6 border-t border-ih-border pt-6">
          {customBody ? (
            <div className="text-[15px] text-ih-fg-2 leading-relaxed whitespace-pre-wrap">
              {customBody}
            </div>
          ) : isPrivacy ? (
            <PrivacyContent company={companyName} />
          ) : (
            <TermsContent company={companyName} />
          )}
        </div>

        <footer className="mt-10 pt-6 border-t border-ih-border">
          <p className="text-xs text-ih-fg-3">
            {m.public_legal_powered_by()}{" "}
            <a
              href="https://openinspection.app"
              className="underline hover:text-ih-fg-2 transition-colors"
            >
              OpenInspection
            </a>
            {m.public_legal_provided_by({ company: companyName })}
          </p>
        </footer>
      </main>
    </div>
  );
}
