/**
 * Design System 0520 subsystem B phase 2 task 2.8 — Durable Object smoke
 * placeholder.
 *
 * Real DO-runtime roster-broadcast coverage now lives in the workerd pool:
 * tests/workers/presence-do.spec.ts (the DO imports `cloudflare:workers`,
 * unavailable in this node env). The DO behaviour is additionally covered by:
 *
 *   1. The protocol helpers (tests/unit/presence-protocol.spec.ts) which
 *      verify the wire-format contract shared between the DO and the
 *      browser clients.
 *   2. A Playwright two-context E2E (subsystem B phase 8) that connects
 *      two browser windows to the same inspection and asserts roster
 *      synchronisation across them.
 *
 * This node-env file keeps only the static binding-contract checks below —
 * they catch regressions where someone refactors the file path / class name
 * without updating wrangler.jsonc's [[durable_objects.bindings]].
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

describe('Presence Durable Objects — smoke', () => {
    it('InspectionPresenceDO class name matches wrangler binding', () => {
        const src = readFileSync(resolve(__dirname, '../../../server/durable-objects/inspection-presence.ts'), 'utf8');
        expect(src).toMatch(/export class InspectionPresenceDO/);
    });

    it('TenantPresenceDO class name matches wrangler binding', () => {
        const src = readFileSync(resolve(__dirname, '../../../server/durable-objects/tenant-presence.ts'), 'utf8');
        expect(src).toMatch(/export class TenantPresenceDO/);
    });

    // Read the .example template (committed) rather than the populated
    // wrangler.jsonc (gitignored, generated by setup). A fresh clone has no
    // wrangler.jsonc until setup runs, but the structural check needs to
    // pass in CI / `npm test` without any setup prerequisite.
    it('wrangler.jsonc binds both classes', () => {
        const cfg = readFileSync(resolve(__dirname, '../../../wrangler.jsonc'), 'utf8');
        expect(cfg).toMatch(/"class_name":\s*"InspectionPresenceDO"/);
        expect(cfg).toMatch(/"class_name":\s*"TenantPresenceDO"/);
    });
});
