/**
 * gen-version.js — reads .git to extract current commit info,
 * then writes server/generated/version.ts before build/deploy.
 *
 * Handles both regular repos and git submodules (.git as a file).
 */
import { execSync } from 'child_process';
import { writeFileSync, mkdirSync, readFileSync, existsSync } from 'fs';
import { join, dirname, resolve } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

function getGitInfo() {
    // Primary: use git command — works for regular repos and submodules alike
    try {
        const commit = execSync('git rev-parse HEAD', { cwd: root, encoding: 'utf8' }).trim();
        let branch = 'unknown';
        try {
            branch = execSync('git rev-parse --abbrev-ref HEAD', { cwd: root, encoding: 'utf8' }).trim();
        } catch { /* detached HEAD in CI — branch stays 'unknown' */ }
        return { commit, shortCommit: commit.slice(0, 7), branch };
    } catch {
        // Fallback: read .git files directly (no git binary available)
        return readGitFiles();
    }
}

function readGitFiles() {
    try {
        let gitDir = join(root, '.git');

        // Submodule: .git is a file containing "gitdir: ../../.git/modules/xxx"
        if (existsSync(gitDir + '/HEAD') === false && existsSync(gitDir)) {
            const pointer = readFileSync(gitDir, 'utf8').trim();
            if (pointer.startsWith('gitdir: ')) {
                gitDir = resolve(root, pointer.slice(8));
            }
        }

        const headContent = readFileSync(join(gitDir, 'HEAD'), 'utf8').trim();
        let commit = 'unknown';
        let branch = 'unknown';

        if (headContent.startsWith('ref: ')) {
            const ref = headContent.slice(5); // e.g. "refs/heads/master"
            branch = ref.replace('refs/heads/', '');

            const refFile = join(gitDir, ref);
            if (existsSync(refFile)) {
                commit = readFileSync(refFile, 'utf8').trim();
            } else {
                // Ref may be in packed-refs
                const packedRefsPath = join(gitDir, 'packed-refs');
                if (existsSync(packedRefsPath)) {
                    const line = readFileSync(packedRefsPath, 'utf8')
                        .split('\n')
                        .find(l => l.endsWith(' ' + ref));
                    if (line) commit = line.split(' ')[0];
                }
            }
        } else {
            // Detached HEAD — headContent is the full SHA
            commit = headContent;
        }

        return { commit, shortCommit: commit.slice(0, 7), branch };
    } catch {
        return { commit: 'unknown', shortCommit: 'unknown', branch: 'unknown' };
    }
}

const { commit, shortCommit, branch } = getGitInfo();
const buildTime = new Date().toISOString();

// Package semver — surfaced at GET /status so a self-hoster can confirm which
// release is running after an upgrade. release-please bumps package.json's
// version on each Release PR, so this constant tracks the tagged release.
let version = '0.0.0';
try {
    version = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8')).version ?? '0.0.0';
} catch { /* package.json unreadable — leave the 0.0.0 sentinel */ }

const outDir = join(root, 'server', 'generated');
mkdirSync(outDir, { recursive: true });

writeFileSync(
    join(outDir, 'version.ts'),
    `// Auto-generated by scripts/gen-version.js — do not edit manually
export const BUILD = {
    version: '${version}',
    commit: '${commit}',
    shortCommit: '${shortCommit}',
    branch: '${branch}',
    buildTime: '${buildTime}',
} as const;
`,
    'utf8',
);

console.log(`[gen-version] commit=${shortCommit} branch=${branch} buildTime=${buildTime}`);
