#!/usr/bin/env node
/**
 * Copies vendor JS libraries and self-hosted font files from node_modules to public/.
 * Run: node scripts/vendor-copy.js
 * Called automatically via `npm run vendor:copy` (and as part of `npm run build`).
 */
import { cpSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const nm = join(root, 'node_modules');
const pub = join(root, 'public');

// ── JS vendor libraries ────────────────────────────────────────────────────────
const vendorDir = join(pub, 'vendor');
mkdirSync(vendorDir, { recursive: true });

const jsFiles = [
  // Alpine, flatpickr, chart, sortable removed — old Hono SSR templates deleted.
  ['swagger-ui-dist/swagger-ui-bundle.js', 'swagger-ui-bundle.js'],
  ['swagger-ui-dist/swagger-ui.css', 'swagger-ui.css'],
  // ExcelJS browser build — loaded on demand by the contacts .xlsx import
  // (script injection, NEVER bundled: ~940KB must stay out of both the worker
  // bundle and the initial client chunk).
  ['exceljs/dist/exceljs.min.js', 'exceljs.min.js'],
];

for (const [src, dest] of jsFiles) {
  cpSync(join(nm, src), join(vendorDir, dest));
  console.log(`  vendor/${dest}`);
}

// Dexie removed — offline IndexedDB code migrated to React Router v7 frontend.

// node-diff3 removed — diff3 three-way merge replaced by projection diffing (FindingDiff).

// Quill, Konva, FullCalendar removed — old Hono SSR templates deleted.

// ── Fonts ───────────────────────────────────────────────────────────────────────
const fontsDir = join(pub, 'fonts');
mkdirSync(fontsDir, { recursive: true });

// Font families and the weights we actually use (latin subset only)
const fonts = [
  { pkg: '@fontsource/inter', weights: [300, 400, 500, 600, 700, 800], italic: false },
  { pkg: '@fontsource/dm-sans', weights: [300, 400, 500, 600, 700], italic: [400] },
  { pkg: '@fontsource/bricolage-grotesque', weights: [300, 400, 500, 600, 700, 800], italic: false },
  { pkg: '@fontsource/jetbrains-mono', weights: [400, 500, 600], italic: false },
  { pkg: '@fontsource/fraunces', weights: [600, 700], italic: false },
  { pkg: '@fontsource/instrument-serif', weights: [400], italic: [400] },
  { pkg: '@fontsource/source-serif-4', weights: [400, 600], italic: false },
];

let cssOut = '/* Auto-generated by scripts/vendor-copy.js — do not edit manually */\n\n';

for (const { pkg, weights, italic } of fonts) {
  const pkgDir = join(nm, pkg);
  const filesDir = join(pkgDir, 'files');
  // font name from package: @fontsource/dm-sans → dm-sans
  const fontSlug = pkg.split('/')[1];

  for (const w of weights) {
    // Normal weight
    const normalCssFile = join(pkgDir, `latin-${w}.css`);
    try {
      const css = readFileSync(normalCssFile, 'utf8');
      // Extract woff2 file references and copy them
      const woff2Matches = css.matchAll(/url\(\.\/files\/([\w-]+\.woff2)\)/g);
      let adjustedCss = css;
      for (const m of woff2Matches) {
        const filename = m[1];
        cpSync(join(filesDir, filename), join(fontsDir, filename));
        adjustedCss = adjustedCss.replace(`./files/${filename}`, `/fonts/${filename}`);
      }
      // Remove woff references (keep only woff2)
      adjustedCss = adjustedCss.replace(/,\s*url\([^)]*\.woff\)\s*format\(['"]woff['"]\)/g, '');
      cssOut += adjustedCss + '\n';
    } catch { /* weight not available */ }

    // Italic variant if needed
    if (italic && italic.includes(w)) {
      const italicCssFile = join(pkgDir, `latin-${w}-italic.css`);
      try {
        const css = readFileSync(italicCssFile, 'utf8');
        const woff2Matches = css.matchAll(/url\(\.\/files\/([\w-]+\.woff2)\)/g);
        let adjustedCss = css;
        for (const m of woff2Matches) {
          const filename = m[1];
          cpSync(join(filesDir, filename), join(fontsDir, filename));
          adjustedCss = adjustedCss.replace(`./files/${filename}`, `/fonts/${filename}`);
        }
        adjustedCss = adjustedCss.replace(/,\s*url\([^)]*\.woff\)\s*format\(['"]woff['"]\)/g, '');
        cssOut += adjustedCss + '\n';
      } catch { /* italic not available */ }
    }
  }

  console.log(`  fonts: ${fontSlug} (${weights.join(', ')})`);
}

writeFileSync(join(pub, 'fonts.css'), cssOut);
console.log('  → public/fonts.css written');
console.log('Done.');
