/**
 * The measuring instrument, measured.
 *
 * `runsInContentStream` is what says where text landed, and every claim this
 * repository makes about a statutory form's geometry is downstream of it. An
 * instrument that reports the wrong coordinate does not fail — it agrees with
 * whatever it is pointed at, and the audit built on top of it comes back clean.
 *
 * The specific reading these fixtures pin down is per-line attribution. A page
 * written by `drawText` puts one `Tm` in each `BT`…`ET`, so a wrapped value's
 * lines legitimately share one origin. A GENERATED FORM-FIELD APPEARANCE does
 * not: pdf-lib writes one `Tm` and one `Tj` per line inside a single text
 * object. Reading the block's first matrix for all of them would place every
 * line at the first line's baseline — and a value whose last line falls out of
 * the bottom of its box would then measure as sitting comfortably inside it.
 * That is the exact reading `scripts/verify-statutory-render.mjs` exists to
 * take, and it was wrong until 2026-08-29.
 *
 * The streams below are literal, not produced: a fixture generated by the same
 * library the parser reads cannot disagree with it.
 */
import { describe, expect, it } from 'vitest';
import { runsInContentStream } from '../helpers/pdf-drawn-runs';

/** `The` in WinAnsi hex, which is what a standard-font `Tj` shows. */
const THE = '546865';
const CAT = '436174';

describe('runsInContentStream', () => {
    it('gives every shown string the matrix most recently set before it', () => {
        const runs = runsInContentStream([
            'BT',
            '/Helvetica 10 Tf',
            '1 0 0 1 1 21.98 Tm',
            `<${THE}> Tj`,
            '1 0 0 1 1 -0.22 Tm',
            `<${CAT}> Tj`,
            'ET',
        ].join('\n'));

        expect(runs).toEqual([
            { text: 'The', x: 1, y: 21.98, size: 10 },
            { text: 'Cat', x: 1, y: -0.22, size: 10 },
        ]);
    });

    it('keeps one origin for lines broken with T*, which is how drawText wraps', () => {
        const runs = runsInContentStream([
            'BT',
            '/Helvetica 9 Tf',
            '8.325 TL',
            '1 0 0 1 45 270 Tm',
            `<${THE}> Tj`,
            'T*',
            `<${CAT}> Tj`,
            'T*',
            'ET',
        ].join('\n'));

        expect(runs).toEqual([
            { text: 'The', x: 45, y: 270, size: 9 },
            { text: 'Cat', x: 45, y: 270, size: 9 },
        ]);
    });

    it('reports a string shown before any matrix as absent rather than guessing', () => {
        // Nothing in the stream says where this is. Emitting it at (0, 0) would
        // put a run at a coordinate no operator asked for, and a coordinate is
        // the only thing that tells a correctly placed value from a wrong one.
        expect(runsInContentStream(`BT\n/Helvetica 10 Tf\n<${THE}> Tj\nET`)).toEqual([]);
        expect(runsInContentStream(`BT\n1 0 0 1 5 5 Tm\n<${THE}> Tj\nET`)).toEqual([]);
    });

    it('reads each text object separately', () => {
        const runs = runsInContentStream([
            `BT\n/Helvetica 8 Tf\n1 0 0 1 10 20 Tm\n<${THE}> Tj\nET`,
            `BT\n/Helvetica 12 Tf\n1 0 0 1 30 40 Tm\n<${CAT}> Tj\nET`,
        ].join('\n'));

        expect(runs).toEqual([
            { text: 'The', x: 10, y: 20, size: 8 },
            { text: 'Cat', x: 30, y: 40, size: 12 },
        ]);
    });

    it('returns nothing for a stream that draws no text — which is a FAILURE to read as such', () => {
        // Pinned because an empty array satisfies every assertion of the form
        // "none of the runs is wrong". The callers assert the runs they expect
        // by value; this is the reading that makes that necessary.
        expect(runsInContentStream('q 1 0 0 1 0 0 cm Q')).toEqual([]);
    });
});
