/**
 * DOM narrowing helpers for the co-located web suite (`app/**` and
 * `packages/shared-ui/src/**` specs, run by `vitest.config.ts`).
 *
 * ⚠️ WHY THIS EXISTS, AND WHY IT IS NOT A CAST.
 *
 * The app tsc program loads lib.dom AND the Workers runtime types in the same
 * global scope. Both `worker-configuration.d.ts` (generated by `wrangler types`)
 * and `@cloudflare/workers-types` declare the HTMLRewriter's `interface Element`,
 * whose members return `Element` so handlers can chain — including
 * `remove(): Element`. TypeScript MERGES that with lib.dom's `interface Element`,
 * whose `remove()` returns `void`. The merge is a conflict (TS2717), but every
 * program in this repo sets `skipLibCheck: true`, so the error is never printed
 * and the inconsistent global survives.
 *
 * The visible consequence is narrow but total: `HTMLSelectElement` is the one
 * lib.dom subtype that RE-DECLARES `remove` (`remove(index: number): void`), so
 * it does not inherit the merged `remove(): Element` and stops being assignable
 * to `HTMLElement`. In this program `el as HTMLSelectElement` is TS2352 in one
 * direction and TS2345 in the other, and even
 * `screen.getByRole<HTMLSelectElement>(…)` fails its `T extends HTMLElement`
 * constraint. Nothing about the SPEC is wrong; the global type graph is.
 *
 * `as unknown as HTMLSelectElement` would compile, and it would also be a
 * suppression that hides the next real mistake at the same call site. An
 * `instanceof` narrowing costs the same line and is strictly stronger: it
 * asserts at RUNTIME that the query really returned a `<select>`, and it yields
 * `HTMLElement & HTMLSelectElement` — an intersection that satisfies both the
 * select-only members the spec came for and the `HTMLElement` parameter of
 * `within()` / the jest-dom matchers.
 *
 * If the merged-`Element` defect is ever fixed at the program level, these stay
 * correct; they just stop being necessary.
 */

/** A `<select>` that is still usable everywhere an `HTMLElement` is expected. */
export type SelectElement = HTMLElement & HTMLSelectElement;

/**
 * Narrow a queried element to `<select>`, failing the test if it is not one.
 *
 * @param el   whatever `getByRole` / `getByLabelText` returned
 * @param what optional description used in the failure message
 */
export function asSelect(el: HTMLElement | null | undefined, what = 'element'): SelectElement {
    if (el && isSelect(el)) return el;
    throw new Error(
        `Expected ${what} to be a <select>, got ${el ? `<${el.tagName.toLowerCase()}>` : String(el)}.`,
    );
}

/**
 * The predicate is a separate function ON PURPOSE. A bare `instanceof` narrows
 * `HTMLElement` to plain `HTMLSelectElement` — which, per the note above, is not
 * assignable to `HTMLElement` here, so returning it from `asSelect` is TS2322. A
 * user-defined guard states the INTERSECTION as the narrowed type, and its own
 * body only has to return a boolean.
 */
function isSelect(el: HTMLElement): el is SelectElement {
    return el instanceof HTMLSelectElement;
}
