import { describe, it, expectTypeOf } from 'vitest';
import type { WorkerEnv } from '../../../workers/env';

type LoadContextEnv = WorkerEnv;

/**
 * Type-only: the env reachable from a React Router loader must be the FULL
 * wrangler-generated `Env`, not a hand-maintained subset.
 *
 * The worker entry augments `AppLoadContext` with the env it passes to
 * `createRequestHandler`. When that augmentation names a locally-declared
 * `interface Env`, the local declaration shadows the global one generated by
 * `wrangler types`, and every `context.cloudflare.env.*` read across the app
 * silently narrows to whatever few fields were hand-listed. Nothing errors —
 * autocompletion just disappears and typos stop being caught, which is exactly
 * the kind of regression a type-only spec exists to pin.
 *
 * Runtime coverage of the bindings actually working lives in the API specs;
 * this file only asserts they are VISIBLE to the loader layer.
 */
describe('React Router load-context env', () => {
  it('exposes the D1 binding', () => {
    expectTypeOf<LoadContextEnv>().toHaveProperty('DB').toEqualTypeOf<D1Database>();
  });

  it('exposes the R2 photo bucket', () => {
    expectTypeOf<LoadContextEnv>().toHaveProperty('PHOTOS').toEqualTypeOf<R2Bucket>();
  });

  it('exposes the tenant-config KV namespace', () => {
    expectTypeOf<LoadContextEnv>().toHaveProperty('TENANT_CACHE').toEqualTypeOf<KVNamespace>();
  });

  it('exposes the static-assets fetcher', () => {
    expectTypeOf<LoadContextEnv>().toHaveProperty('ASSETS');
  });

  /**
   * These three are NOT emitted by `wrangler types`, so they must be declared
   * explicitly alongside the generated Env rather than replacing it:
   *   - API_WORKER is injected in-process by the worker entry (never a binding).
   *   - SESSION_SECRET / API_URL live only in the gitignored wrangler.local /
   *     wrangler.saas configs, so typegen against the committed placeholder
   *     never sees them.
   */
  it('exposes the in-process API self-binding', () => {
    expectTypeOf<LoadContextEnv>().toHaveProperty('API_WORKER');
  });

  it('exposes the session secret', () => {
    expectTypeOf<LoadContextEnv>().toHaveProperty('SESSION_SECRET');
  });
});
