/**
 * Florida OIR-B1-1802 uniform mitigation verification inspection form
 * (Rev. 04/26) -- the published revision and the map checked against it.
 *
 * -- GENERATED FROM THE SIGNED CANDIDATE, NOT TYPED BY HAND ------------------
 * The 241 mappings below were emitted from the artifact a person signed
 * (`checkedBy: Nathan`, 2026-08-30) rather than copied. Hand-copying would
 * introduce differences the signature does not cover, and this file exists to
 * carry that signature into the software unchanged.
 *
 * -- WHICH PDF THIS IS ------------------------------------------------------
 * The six-page adopted version the Office publishes without a watermark. It is
 * NOT the file at the guessable path under the same forms directory: that one
 * is the superseded Rev. 01/12, and it is the reason `sourceHash` exists. Both
 * open, both look official, and a map authored against one of them would move
 * content into boxes nobody measured on the other.
 *
 * -- THE PARTED OVERLAYS ----------------------------------------------------
 * This form prints its own separators: a date is three blanks with the form's
 * slashes in the 2.8pt gaps between them. One overlay covering all three writes
 * the year across the wrong blank and leaves the year's own blank empty, so
 * those values are written as one overlay per printed blank, carrying `part`.
 * Entry stays a single date box -- see `value-parts.ts`.
 *
 * -- THE HASH IS WRITTEN TWICE, ON PURPOSE ----------------------------------
 * Once on the revision and once on the map. A shared constant would make them
 * impossible to diverge -- and would also make that impossible to CHECK:
 * `check-statutory-fidelity.mjs` reads sha256 literals, and a constant it
 * cannot resolve reads to it as a file declaring none.
 *
 * -- THE DATES ARE THE RULE'S OWN -------------------------------------------
 * Rule 69O-170.0155, F.A.C. adopts this form by reference. Its rule history
 * reads "History-New 6-19-03, Formerly 4-170.0155, Amended 2-23-06, ...,
 * 3-25-13, 4-1-26", and the rule's current effective date is 4/1/2026.
 *
 * `mandatoryFrom` is the SAME day as `effectiveFrom`, where TREC's two differ.
 * TREC published two dates with a voluntary window between them; this rule
 * publishes one. The amendment struck Rev. 01/12 out of the rule text and put
 * Rev. 04/26 in its place, so from 4/1/2026 the only revision incorporated by
 * reference is this one -- there is no window for the older revision to sit in.
 * ⚠️ That last step is an inference from a STRIKETHROUGH, not from a sentence
 * saying "required from". It is written here so the next reader can challenge
 * it: a transition clause found in the rule text would change `mandatoryFrom`
 * and would leave `effectiveFrom` alone.
 *
 * ⚠️ NOTHING DECLARES THIS FORM YET, exactly as for the other three.
 */
import type { StatutoryFormVersion } from '../form-registry';
import type { FieldMap } from '../field-map';

export const version: StatutoryFormVersion = {
    formId: 'fl_oir_b1_1802',
    // The Office's own title for the adopted form, as the form prints it.
    formTitle: 'Florida Office of Insurance Regulation Uniform Mitigation Verification Inspection Form',
    version: 'Rev. 04/26',
    // Rule 69O-170.0155, F.A.C., amended 4-1-26. One date, not two: the
    // amendment replaced Rev. 01/12 in the rule text rather than running a
    // voluntary window beside it.
    effectiveFrom: Date.UTC(2026, 3, 1),
    mandatoryFrom: Date.UTC(2026, 3, 1),
    // Still current: the Office has published no successor as of the publish date.
    effectiveUntil: null,
    withdrawn: null,
    sourceUrl: 'https://floir.gov/docs-sf/property-casualty-libraries/product-review/all-forms/form-oir-1802-adopted-version-(no-watermark).pdf?Status=Master',
    sourceHash: 'e02320a4f6d6f5d3f72de07e5a3d2955e9bb3ae97a35576dfcc4b64d04177e5c',
    publishedBy: 'InspectorHub',
    publishedAt: Date.UTC(2026, 7, 30),
};

export const fieldMap: FieldMap = {
    formId: 'fl_oir_b1_1802',
    version: 'Rev. 04/26',
    // Written a SECOND time on purpose. See the file header.
    sourceHash: 'e02320a4f6d6f5d3f72de07e5a3d2955e9bb3ae97a35576dfcc4b64d04177e5c',
    checkedBy: 'Nathan',
    checkedAt: Date.UTC(2026, 7, 30),
    requiredFields: [
        'property_address',
        'inspection_date',
        'owner_name',
        'year_of_home',
        'number_of_stories',
        'building_code',
        'wind_region',
        'roof_slope',
        'roof_covering_types',
        'roof_covering_product_approval',
        'roof_deck_attachment',
        'roof_wall_attachment',
        'roof_geometry',
        'sealed_roof_deck',
        'opening_protection',
        'inspector_name',
        'inspector_license_type',
        'inspector_license_number',
        'inspector_qualification',
        'inspector_signature_date',
    ],
    mappings: [
        { kind: 'overlay', ourField: 'inspector_initials', page: 0, x: 116.8, y: 70.72, size: 9.0, maxWidth: 54.3, maxHeight: 11.0 },
        { kind: 'overlay', ourField: 'property_address', page: 0, x: 250.26, y: 70.72, size: 9.0, maxWidth: 319.1, maxHeight: 11.0 },
        { kind: 'overlay', ourField: 'inspector_initials', page: 1, x: 116.8, y: 70.72, size: 9.0, maxWidth: 54.3, maxHeight: 11.0 },
        { kind: 'overlay', ourField: 'property_address', page: 1, x: 250.26, y: 70.72, size: 9.0, maxWidth: 319.1, maxHeight: 11.0 },
        { kind: 'overlay', ourField: 'inspector_initials', page: 2, x: 116.8, y: 70.72, size: 9.0, maxWidth: 54.3, maxHeight: 11.0 },
        { kind: 'overlay', ourField: 'property_address', page: 2, x: 250.26, y: 70.72, size: 9.0, maxWidth: 319.1, maxHeight: 11.0 },
        { kind: 'overlay', ourField: 'inspector_initials', page: 3, x: 116.8, y: 70.72, size: 9.0, maxWidth: 54.3, maxHeight: 11.0 },
        { kind: 'overlay', ourField: 'property_address', page: 3, x: 250.26, y: 70.72, size: 9.0, maxWidth: 319.1, maxHeight: 11.0 },
        { kind: 'overlay', ourField: 'inspector_initials', page: 4, x: 116.8, y: 70.72, size: 9.0, maxWidth: 54.3, maxHeight: 11.0 },
        { kind: 'overlay', ourField: 'property_address', page: 4, x: 250.26, y: 70.72, size: 9.0, maxWidth: 319.1, maxHeight: 11.0 },
        { kind: 'overlay', ourField: 'inspector_initials', page: 5, x: 116.8, y: 70.72, size: 9.0, maxWidth: 54.3, maxHeight: 11.0 },
        { kind: 'overlay', ourField: 'property_address', page: 5, x: 250.26, y: 70.72, size: 9.0, maxWidth: 319.1, maxHeight: 11.0 },
        { kind: 'overlay', ourField: 'inspection_date', page: 0, x: 130.0, y: 724.2, size: 10.0, maxWidth: 437.3, maxHeight: 12.0 },
        { kind: 'overlay', ourField: 'owner_name', page: 0, x: 116.9, y: 680.0, size: 10.0, maxWidth: 231.3, maxHeight: 12.0 },
        { kind: 'overlay', ourField: 'contact_person', page: 0, x: 439.2, y: 680.0, size: 10.0, maxWidth: 128.1, maxHeight: 12.0 },
        { kind: 'overlay', ourField: 'owner_mailing_address', page: 0, x: 94.0, y: 657.9, size: 10.0, maxWidth: 254.2, maxHeight: 12.0 },
        { kind: 'overlay', ourField: 'owner_home_phone', page: 0, x: 426.7, y: 657.9, size: 10.0, maxWidth: 140.6, maxHeight: 12.0 },
        { kind: 'overlay', ourField: 'owner_city', page: 0, x: 76.8, y: 635.8, size: 10.0, maxWidth: 115.5, maxHeight: 12.0 },
        { kind: 'overlay', ourField: 'owner_zip', page: 0, x: 229.0, y: 635.8, size: 10.0, maxWidth: 119.2, maxHeight: 12.0 },
        { kind: 'overlay', ourField: 'owner_work_phone', page: 0, x: 424.8, y: 635.8, size: 10.0, maxWidth: 142.5, maxHeight: 12.0 },
        { kind: 'overlay', ourField: 'owner_county', page: 0, x: 90.2, y: 613.7, size: 10.0, maxWidth: 258.0, maxHeight: 12.0 },
        { kind: 'overlay', ourField: 'owner_cell_phone', page: 0, x: 418.1, y: 613.7, size: 10.0, maxWidth: 149.2, maxHeight: 12.0 },
        { kind: 'overlay', ourField: 'insurance_company', page: 0, x: 146.2, y: 591.6, size: 10.0, maxWidth: 202.0, maxHeight: 12.0 },
        { kind: 'overlay', ourField: 'policy_number', page: 0, x: 406.0, y: 591.6, size: 10.0, maxWidth: 161.3, maxHeight: 12.0 },
        { kind: 'overlay', ourField: 'year_of_home', page: 0, x: 120.8, y: 569.4, size: 10.0, maxWidth: 71.5, maxHeight: 12.0 },
        { kind: 'overlay', ourField: 'number_of_stories', page: 0, x: 264.4, y: 569.4, size: 10.0, maxWidth: 83.8, maxHeight: 12.0 },
        { kind: 'overlay', ourField: 'owner_email', page: 0, x: 395.8, y: 569.4, size: 10.0, maxWidth: 171.5, maxHeight: 12.0 },
        { kind: 'checkbox', ourField: 'fortified_certificate', whenValue: 'roof', page: 0, x: 287.35, y: 531.57, size: 4.5 },
        { kind: 'checkbox', ourField: 'fortified_certificate', whenValue: 'silver', page: 0, x: 322.99, y: 531.57, size: 4.5 },
        { kind: 'checkbox', ourField: 'fortified_certificate', whenValue: 'gold', page: 0, x: 375.68, y: 531.57, size: 4.5 },
        { kind: 'checkbox', ourField: 'building_code', whenValue: 'A', page: 0, x: 37.51, y: 451.05, size: 4.5 },
        { kind: 'checkbox', ourField: 'building_code', whenValue: 'B', page: 0, x: 37.5, y: 428.0, size: 4.5 },
        { kind: 'checkbox', ourField: 'building_code', whenValue: 'C', page: 0, x: 37.5, y: 405.08, size: 4.5 },
        { kind: 'checkbox', ourField: 'building_code', whenValue: 'D', page: 0, x: 37.51, y: 370.52, size: 4.5 },
        { kind: 'overlay', ourField: 'building_code_a_year_built', page: 0, x: 402.15, y: 451.36, size: 9.0, maxWidth: 44.1, maxHeight: 11.0 },
        { kind: 'overlay', ourField: 'building_code_b_year_built', page: 0, x: 403.0, y: 428.32, size: 9.0, maxWidth: 44.1, maxHeight: 11.0 },
        { kind: 'overlay', ourField: 'building_code_c_year_built', page: 0, x: 442.48, y: 405.4, size: 9.0, maxWidth: 29.1, maxHeight: 11.0 },
        { kind: 'overlay', ourField: 'building_code_a_permit_application_date', page: 0, x: 472.2, y: 439.84, size: 9.0, maxWidth: 20.1, maxHeight: 11.0, part: 'date_month' },
        { kind: 'overlay', ourField: 'building_code_a_permit_application_date', page: 0, x: 495.12, y: 439.84, size: 9.0, maxWidth: 19.98, maxHeight: 11.0, part: 'date_day' },
        { kind: 'overlay', ourField: 'building_code_a_permit_application_date', page: 0, x: 517.8, y: 439.84, size: 9.0, maxWidth: 40.02, maxHeight: 11.0, part: 'date_year' },
        { kind: 'overlay', ourField: 'building_code_b_permit_application_date', page: 0, x: 477.12, y: 416.91, size: 9.0, maxWidth: 20.1, maxHeight: 11.0, part: 'date_month' },
        { kind: 'overlay', ourField: 'building_code_b_permit_application_date', page: 0, x: 500.04, y: 416.91, size: 9.0, maxWidth: 19.98, maxHeight: 11.0, part: 'date_day' },
        { kind: 'overlay', ourField: 'building_code_b_permit_application_date', page: 0, x: 522.72, y: 416.91, size: 9.0, maxWidth: 40.14, maxHeight: 11.0, part: 'date_year' },
        { kind: 'overlay', ourField: 'building_code_c_permit_application_date', page: 0, x: 36.0, y: 382.36, size: 9.0, maxWidth: 15.06, maxHeight: 11.0, part: 'date_month' },
        { kind: 'overlay', ourField: 'building_code_c_permit_application_date', page: 0, x: 53.88, y: 382.36, size: 9.0, maxWidth: 14.94, maxHeight: 11.0, part: 'date_day' },
        { kind: 'overlay', ourField: 'building_code_c_permit_application_date', page: 0, x: 71.64, y: 382.36, size: 9.0, maxWidth: 34.98, maxHeight: 11.0, part: 'date_year' },
        { kind: 'checkbox', ourField: 'wind_region', whenValue: 'hvhz', page: 0, x: 37.51, y: 336.09, size: 4.5 },
        { kind: 'checkbox', ourField: 'wind_region', whenValue: 'region_1', page: 0, x: 81.31, y: 336.09, size: 4.5 },
        { kind: 'checkbox', ourField: 'wind_region', whenValue: 'region_2', page: 0, x: 181.87, y: 336.09, size: 4.5 },
        { kind: 'checkbox', ourField: 'wind_region', whenValue: 'region_3', page: 0, x: 319.51, y: 336.09, size: 4.5 },
        { kind: 'checkbox', ourField: 'roof_slope', whenValue: 'gte_6_12', page: 0, x: 37.51, y: 290.13, size: 4.5 },
        { kind: 'checkbox', ourField: 'roof_slope', whenValue: 'lt_6_12', page: 0, x: 178.49, y: 290.13, size: 4.5 },
        { kind: 'checkbox', ourField: 'roof_covering_types', whenValue: 'asphalt_fiberglass_shingle', page: 0, x: 42.78, y: 205.85, size: 4.0 },
        { kind: 'checkbox', ourField: 'roof_covering_asphalt_fiberglass_shingle_no_information', whenValue: 'true', page: 0, x: 467.71, y: 200.68, size: 4.0 },
        { kind: 'overlay', ourField: 'roof_covering_asphalt_fiberglass_shingle_permit_application_date', page: 0, x: 166.92, y: 201.0, size: 8.0, maxWidth: 18.07, maxHeight: 10.3, part: 'date_month' },
        { kind: 'overlay', ourField: 'roof_covering_asphalt_fiberglass_shingle_permit_application_date', page: 0, x: 187.45, y: 201.0, size: 8.0, maxWidth: 18.07, maxHeight: 10.3, part: 'date_day' },
        { kind: 'overlay', ourField: 'roof_covering_asphalt_fiberglass_shingle_permit_application_date', page: 0, x: 207.98, y: 201.0, size: 8.0, maxWidth: 18.07, maxHeight: 10.3, part: 'date_year' },
        { kind: 'overlay', ourField: 'roof_covering_asphalt_fiberglass_shingle_product_approval_number', page: 0, x: 247.6, y: 201.0, size: 9.0, maxWidth: 73.0, maxHeight: 11.0 },
        { kind: 'overlay', ourField: 'roof_covering_asphalt_fiberglass_shingle_year_installed', page: 0, x: 349.1, y: 201.0, size: 9.0, maxWidth: 73.0, maxHeight: 11.0 },
        { kind: 'checkbox', ourField: 'roof_covering_types', whenValue: 'concrete_clay_tile', page: 0, x: 42.78, y: 185.09, size: 4.0 },
        { kind: 'checkbox', ourField: 'roof_covering_concrete_clay_tile_no_information', whenValue: 'true', page: 0, x: 467.7, y: 185.09, size: 4.0 },
        { kind: 'overlay', ourField: 'roof_covering_concrete_clay_tile_permit_application_date', page: 0, x: 166.92, y: 185.4, size: 8.0, maxWidth: 18.07, maxHeight: 10.3, part: 'date_month' },
        { kind: 'overlay', ourField: 'roof_covering_concrete_clay_tile_permit_application_date', page: 0, x: 187.45, y: 185.4, size: 8.0, maxWidth: 18.07, maxHeight: 10.3, part: 'date_day' },
        { kind: 'overlay', ourField: 'roof_covering_concrete_clay_tile_permit_application_date', page: 0, x: 207.98, y: 185.4, size: 8.0, maxWidth: 18.07, maxHeight: 10.3, part: 'date_year' },
        { kind: 'overlay', ourField: 'roof_covering_concrete_clay_tile_product_approval_number', page: 0, x: 247.6, y: 185.4, size: 9.0, maxWidth: 73.0, maxHeight: 11.0 },
        { kind: 'overlay', ourField: 'roof_covering_concrete_clay_tile_year_installed', page: 0, x: 349.1, y: 185.4, size: 9.0, maxWidth: 73.0, maxHeight: 11.0 },
        { kind: 'checkbox', ourField: 'roof_covering_types', whenValue: 'synthetic_composite_tile', page: 0, x: 42.78, y: 174.76, size: 4.0 },
        { kind: 'checkbox', ourField: 'roof_covering_synthetic_composite_tile_no_information', whenValue: 'true', page: 0, x: 467.7, y: 174.76, size: 4.0 },
        { kind: 'overlay', ourField: 'roof_covering_synthetic_composite_tile_permit_application_date', page: 0, x: 166.92, y: 175.1, size: 8.0, maxWidth: 18.07, maxHeight: 10.3, part: 'date_month' },
        { kind: 'overlay', ourField: 'roof_covering_synthetic_composite_tile_permit_application_date', page: 0, x: 187.45, y: 175.1, size: 8.0, maxWidth: 18.07, maxHeight: 10.3, part: 'date_day' },
        { kind: 'overlay', ourField: 'roof_covering_synthetic_composite_tile_permit_application_date', page: 0, x: 207.98, y: 175.1, size: 8.0, maxWidth: 18.07, maxHeight: 10.3, part: 'date_year' },
        { kind: 'overlay', ourField: 'roof_covering_synthetic_composite_tile_product_approval_number', page: 0, x: 247.6, y: 175.1, size: 9.0, maxWidth: 73.0, maxHeight: 11.0 },
        { kind: 'overlay', ourField: 'roof_covering_synthetic_composite_tile_year_installed', page: 0, x: 349.1, y: 175.1, size: 9.0, maxWidth: 73.0, maxHeight: 11.0 },
        { kind: 'checkbox', ourField: 'roof_covering_types', whenValue: 'metal', page: 0, x: 42.78, y: 164.44, size: 4.0 },
        { kind: 'checkbox', ourField: 'roof_covering_metal_no_information', whenValue: 'true', page: 0, x: 467.7, y: 164.44, size: 4.0 },
        { kind: 'overlay', ourField: 'roof_covering_metal_permit_application_date', page: 0, x: 166.92, y: 164.8, size: 8.0, maxWidth: 18.07, maxHeight: 10.3, part: 'date_month' },
        { kind: 'overlay', ourField: 'roof_covering_metal_permit_application_date', page: 0, x: 187.45, y: 164.8, size: 8.0, maxWidth: 18.07, maxHeight: 10.3, part: 'date_day' },
        { kind: 'overlay', ourField: 'roof_covering_metal_permit_application_date', page: 0, x: 207.98, y: 164.8, size: 8.0, maxWidth: 18.07, maxHeight: 10.3, part: 'date_year' },
        { kind: 'overlay', ourField: 'roof_covering_metal_product_approval_number', page: 0, x: 247.6, y: 164.8, size: 9.0, maxWidth: 73.0, maxHeight: 11.0 },
        { kind: 'overlay', ourField: 'roof_covering_metal_year_installed', page: 0, x: 349.1, y: 164.8, size: 9.0, maxWidth: 73.0, maxHeight: 11.0 },
        { kind: 'checkbox', ourField: 'roof_covering_types', whenValue: 'built_up', page: 0, x: 42.78, y: 154.12, size: 4.0 },
        { kind: 'checkbox', ourField: 'roof_covering_built_up_no_information', whenValue: 'true', page: 0, x: 467.7, y: 154.12, size: 4.0 },
        { kind: 'overlay', ourField: 'roof_covering_built_up_permit_application_date', page: 0, x: 166.92, y: 154.5, size: 8.0, maxWidth: 18.07, maxHeight: 10.3, part: 'date_month' },
        { kind: 'overlay', ourField: 'roof_covering_built_up_permit_application_date', page: 0, x: 187.45, y: 154.5, size: 8.0, maxWidth: 18.07, maxHeight: 10.3, part: 'date_day' },
        { kind: 'overlay', ourField: 'roof_covering_built_up_permit_application_date', page: 0, x: 207.98, y: 154.5, size: 8.0, maxWidth: 18.07, maxHeight: 10.3, part: 'date_year' },
        { kind: 'overlay', ourField: 'roof_covering_built_up_product_approval_number', page: 0, x: 247.6, y: 154.5, size: 9.0, maxWidth: 73.0, maxHeight: 11.0 },
        { kind: 'overlay', ourField: 'roof_covering_built_up_year_installed', page: 0, x: 349.1, y: 154.5, size: 9.0, maxWidth: 73.0, maxHeight: 11.0 },
        { kind: 'checkbox', ourField: 'roof_covering_types', whenValue: 'membrane', page: 0, x: 42.78, y: 143.68, size: 4.0 },
        { kind: 'checkbox', ourField: 'roof_covering_membrane_no_information', whenValue: 'true', page: 0, x: 467.7, y: 143.68, size: 4.0 },
        { kind: 'overlay', ourField: 'roof_covering_membrane_permit_application_date', page: 0, x: 166.92, y: 144.0, size: 8.0, maxWidth: 18.07, maxHeight: 10.3, part: 'date_month' },
        { kind: 'overlay', ourField: 'roof_covering_membrane_permit_application_date', page: 0, x: 187.45, y: 144.0, size: 8.0, maxWidth: 18.07, maxHeight: 10.3, part: 'date_day' },
        { kind: 'overlay', ourField: 'roof_covering_membrane_permit_application_date', page: 0, x: 207.98, y: 144.0, size: 8.0, maxWidth: 18.07, maxHeight: 10.3, part: 'date_year' },
        { kind: 'overlay', ourField: 'roof_covering_membrane_product_approval_number', page: 0, x: 247.6, y: 144.0, size: 9.0, maxWidth: 73.0, maxHeight: 11.0 },
        { kind: 'overlay', ourField: 'roof_covering_membrane_year_installed', page: 0, x: 349.1, y: 144.0, size: 9.0, maxWidth: 73.0, maxHeight: 11.0 },
        { kind: 'checkbox', ourField: 'roof_covering_types', whenValue: 'other', page: 0, x: 42.78, y: 128.2, size: 4.0 },
        { kind: 'checkbox', ourField: 'roof_covering_other_no_information', whenValue: 'true', page: 0, x: 467.7, y: 133.36, size: 4.0 },
        { kind: 'overlay', ourField: 'roof_covering_other_permit_application_date', page: 0, x: 166.92, y: 128.6, size: 8.0, maxWidth: 18.07, maxHeight: 10.3, part: 'date_month' },
        { kind: 'overlay', ourField: 'roof_covering_other_permit_application_date', page: 0, x: 187.45, y: 128.6, size: 8.0, maxWidth: 18.07, maxHeight: 10.3, part: 'date_day' },
        { kind: 'overlay', ourField: 'roof_covering_other_permit_application_date', page: 0, x: 207.98, y: 128.6, size: 8.0, maxWidth: 18.07, maxHeight: 10.3, part: 'date_year' },
        { kind: 'overlay', ourField: 'roof_covering_other_product_approval_number', page: 0, x: 247.6, y: 128.6, size: 9.0, maxWidth: 73.0, maxHeight: 11.0 },
        { kind: 'overlay', ourField: 'roof_covering_other_year_installed', page: 0, x: 349.1, y: 128.6, size: 9.0, maxWidth: 73.0, maxHeight: 11.0 },
        { kind: 'overlay', ourField: 'roof_covering_other_description', page: 0, x: 74.58, y: 128.56, size: 9.0, maxWidth: 57.6, maxHeight: 11.0 },
        { kind: 'checkbox', ourField: 'roof_covering_product_approval', whenValue: 'A', page: 1, x: 37.51, y: 708.81, size: 4.5 },
        { kind: 'checkbox', ourField: 'roof_covering_product_approval', whenValue: 'B', page: 1, x: 37.5, y: 685.88, size: 4.5 },
        { kind: 'checkbox', ourField: 'roof_covering_product_approval', whenValue: 'C', page: 1, x: 37.51, y: 662.84, size: 4.5 },
        { kind: 'checkbox', ourField: 'roof_covering_product_approval', whenValue: 'D', page: 1, x: 37.51, y: 651.33, size: 4.5 },
        { kind: 'checkbox', ourField: 'roof_deck_attachment', whenValue: 'A', page: 1, x: 37.51, y: 616.89, size: 4.5 },
        { kind: 'checkbox', ourField: 'roof_deck_attachment', whenValue: 'B', page: 1, x: 37.49, y: 547.86, size: 4.5 },
        { kind: 'checkbox', ourField: 'roof_deck_attachment', whenValue: 'C', page: 1, x: 37.5, y: 501.91, size: 4.5 },
        { kind: 'checkbox', ourField: 'roof_deck_attachment', whenValue: 'D', page: 1, x: 37.49, y: 444.31, size: 4.5 },
        { kind: 'checkbox', ourField: 'roof_deck_attachment', whenValue: 'E', page: 1, x: 37.51, y: 432.92, size: 4.5 },
        { kind: 'checkbox', ourField: 'roof_deck_attachment', whenValue: 'F', page: 1, x: 37.52, y: 409.88, size: 4.5 },
        { kind: 'checkbox', ourField: 'roof_deck_attachment', whenValue: 'G', page: 1, x: 37.5, y: 398.36, size: 4.5 },
        { kind: 'checkbox', ourField: 'roof_deck_attachment', whenValue: 'H', page: 1, x: 37.51, y: 386.84, size: 4.5 },
        { kind: 'overlay', ourField: 'roof_deck_attachment_other_description', page: 1, x: 85.14, y: 410.19, size: 9.0, maxWidth: 314.1, maxHeight: 11.0 },
        { kind: 'checkbox', ourField: 'roof_wall_attachment', whenValue: 'A', page: 1, x: 37.51, y: 317.84, size: 4.5 },
        { kind: 'checkbox', ourField: 'roof_wall_attachment_toenail_basis', whenValue: 'toenail_driven_at_angle', page: 1, x: 73.5, y: 306.32, size: 4.5 },
        { kind: 'checkbox', ourField: 'roof_wall_attachment_toenail_basis', whenValue: 'connectors_not_installed_as_intended', page: 1, x: 73.49, y: 283.39, size: 4.5 },
        { kind: 'checkbox', ourField: 'roof_wall_attachment_toenail_basis', whenValue: 'documented_185_lb_uplift', page: 1, x: 73.5, y: 260.34, size: 4.5 },
        { kind: 'checkbox', ourField: 'roof_wall_attachment_minimal_condition', whenValue: '1', page: 1, x: 73.5, y: 202.88, size: 4.5 },
        { kind: 'checkbox', ourField: 'roof_wall_attachment_minimal_condition', whenValue: '2', page: 1, x: 73.51, y: 168.43, size: 4.5 },
        { kind: 'checkbox', ourField: 'roof_wall_attachment_minimal_condition', whenValue: '3', page: 1, x: 73.51, y: 145.38, size: 4.5 },
        { kind: 'checkbox', ourField: 'roof_wall_attachment', whenValue: 'B', page: 2, x: 37.51, y: 720.32, size: 4.5 },
        { kind: 'checkbox', ourField: 'roof_wall_attachment_clip_basis', whenValue: 'no_wrap_over_truss', page: 2, x: 73.49, y: 697.4, size: 4.5 },
        { kind: 'checkbox', ourField: 'roof_wall_attachment_clip_basis', whenValue: 'one_wrap_min_three_nails', page: 2, x: 73.48, y: 685.87, size: 4.5 },
        { kind: 'checkbox', ourField: 'roof_wall_attachment_clip_basis', whenValue: 'documented_386_lb_uplift', page: 2, x: 73.48, y: 662.82, size: 4.5 },
        { kind: 'checkbox', ourField: 'roof_wall_attachment', whenValue: 'C', page: 2, x: 37.48, y: 628.37, size: 4.5 },
        { kind: 'checkbox', ourField: 'roof_wall_attachment_single_wrap_basis', whenValue: 'single_strap_two_and_one_nails', page: 2, x: 73.46, y: 616.85, size: 4.5 },
        { kind: 'checkbox', ourField: 'roof_wall_attachment_single_wrap_basis', whenValue: 'documented_535_lb_uplift', page: 2, x: 73.44, y: 593.8, size: 4.5 },
        { kind: 'checkbox', ourField: 'roof_wall_attachment', whenValue: 'D', page: 2, x: 37.44, y: 559.35, size: 4.5 },
        { kind: 'checkbox', ourField: 'roof_wall_attachment_double_wrap_basis', whenValue: 'two_separate_straps', page: 2, x: 73.43, y: 547.83, size: 4.5 },
        { kind: 'checkbox', ourField: 'roof_wall_attachment_double_wrap_basis', whenValue: 'single_strap_three_nails_each_side', page: 2, x: 73.43, y: 513.26, size: 4.5 },
        { kind: 'checkbox', ourField: 'roof_wall_attachment_double_wrap_basis', whenValue: 'documented_891_lb_uplift', page: 2, x: 73.43, y: 490.33, size: 4.5 },
        { kind: 'checkbox', ourField: 'roof_wall_attachment', whenValue: 'E', page: 2, x: 37.43, y: 467.28, size: 4.5 },
        { kind: 'checkbox', ourField: 'roof_wall_attachment', whenValue: 'F', page: 2, x: 37.42, y: 455.76, size: 4.5 },
        { kind: 'checkbox', ourField: 'roof_wall_attachment', whenValue: 'G', page: 2, x: 37.42, y: 444.23, size: 4.5 },
        { kind: 'checkbox', ourField: 'roof_wall_attachment', whenValue: 'H', page: 2, x: 37.42, y: 432.83, size: 4.5 },
        { kind: 'checkbox', ourField: 'roof_wall_attachment', whenValue: 'I', page: 2, x: 37.42, y: 421.3, size: 4.5 },
        { kind: 'overlay', ourField: 'roof_wall_attachment_other_description', page: 2, x: 84.56, y: 456.07, size: 9.0, maxWidth: 234.0, maxHeight: 11.0 },
        { kind: 'checkbox', ourField: 'roof_geometry', whenValue: 'A', page: 2, x: 37.51, y: 363.93, size: 4.5 },
        { kind: 'checkbox', ourField: 'roof_geometry', whenValue: 'B', page: 2, x: 37.5, y: 340.88, size: 4.5 },
        { kind: 'checkbox', ourField: 'roof_geometry', whenValue: 'C', page: 2, x: 37.5, y: 317.84, size: 4.5 },
        { kind: 'overlay', ourField: 'roof_geometry_non_hip_length_ft', page: 2, x: 241.97, y: 352.72, size: 9.0, maxWidth: 29.1, maxHeight: 11.0 },
        { kind: 'overlay', ourField: 'roof_geometry_total_perimeter_ft', page: 2, x: 411.53, y: 352.72, size: 9.0, maxWidth: 34.0, maxHeight: 11.0 },
        { kind: 'overlay', ourField: 'roof_geometry_low_slope_area_sqft', page: 2, x: 275.34, y: 329.68, size: 9.0, maxWidth: 39.0, maxHeight: 11.0 },
        { kind: 'overlay', ourField: 'roof_geometry_total_roof_area_sqft', page: 2, x: 402.54, y: 329.68, size: 9.0, maxWidth: 28.9, maxHeight: 11.0 },
        { kind: 'checkbox', ourField: 'sealed_roof_deck', whenValue: 'A', page: 2, x: 37.51, y: 260.36, size: 4.5 },
        { kind: 'checkbox', ourField: 'sealed_roof_deck_method', whenValue: 'fully_adhered_astm_d1970', page: 2, x: 73.51, y: 248.84, size: 4.5 },
        { kind: 'checkbox', ourField: 'sealed_roof_deck_method', whenValue: 'taped_deck_seams', page: 2, x: 73.49, y: 237.44, size: 4.5 },
        { kind: 'checkbox', ourField: 'sealed_roof_deck_method', whenValue: 'double_layer_no_tape', page: 2, x: 73.47, y: 202.87, size: 4.5 },
        { kind: 'checkbox', ourField: 'sealed_roof_deck_method', whenValue: 'spray_foam', page: 2, x: 73.45, y: 179.82, size: 4.5 },
        { kind: 'checkbox', ourField: 'sealed_roof_deck_spray_foam_underside_fully_covered', whenValue: 'true', page: 2, x: 109.44, y: 168.42, size: 4.5 },
        { kind: 'checkbox', ourField: 'sealed_roof_deck', whenValue: 'B', page: 2, x: 37.44, y: 156.89, size: 4.5 },
        { kind: 'checkbox', ourField: 'sealed_roof_deck', whenValue: 'C', page: 2, x: 37.51, y: 145.4, size: 4.5 },
        { kind: 'checkbox', ourField: 'opening_protection', whenValue: 'A', page: 3, x: 37.51, y: 378.81, size: 4.5 },
        { kind: 'checkbox', ourField: 'opening_protection_non_glazed_level', whenValue: 'A.1', page: 3, x: 67.51, y: 245.01, size: 4.5 },
        { kind: 'checkbox', ourField: 'opening_protection_non_glazed_level', whenValue: 'A.2', page: 3, x: 67.51, y: 233.61, size: 4.5 },
        { kind: 'checkbox', ourField: 'opening_protection_non_glazed_level', whenValue: 'A.3', page: 3, x: 67.51, y: 211.65, size: 4.5 },
        { kind: 'checkbox', ourField: 'opening_protection', whenValue: 'B', page: 3, x: 37.51, y: 189.81, size: 4.5 },
        { kind: 'checkbox', ourField: 'opening_protection_non_glazed_level', whenValue: 'B.1', page: 3, x: 67.51, y: 89.01, size: 4.5 },
        { kind: 'checkbox', ourField: 'opening_protection_non_glazed_level', whenValue: 'B.2', page: 4, x: 67.51, y: 731.85, size: 4.5 },
        { kind: 'checkbox', ourField: 'opening_protection_non_glazed_level', whenValue: 'B.3', page: 4, x: 67.51, y: 710.01, size: 4.5 },
        { kind: 'checkbox', ourField: 'opening_protection', whenValue: 'C', page: 4, x: 37.51, y: 688.17, size: 4.5 },
        { kind: 'checkbox', ourField: 'opening_protection_wood_panel_type', whenValue: 'plywood', page: 4, x: 73.51, y: 676.65, size: 4.5 },
        { kind: 'checkbox', ourField: 'opening_protection_wood_panel_type', whenValue: 'osb', page: 4, x: 137.22, y: 676.65, size: 4.5 },
        { kind: 'checkbox', ourField: 'opening_protection_non_glazed_level', whenValue: 'C.1', page: 4, x: 85.5, y: 653.6, size: 4.5 },
        { kind: 'checkbox', ourField: 'opening_protection_non_glazed_level', whenValue: 'C.2', page: 4, x: 85.51, y: 642.21, size: 4.5 },
        { kind: 'checkbox', ourField: 'opening_protection_non_glazed_level', whenValue: 'C.3', page: 4, x: 85.51, y: 620.37, size: 4.5 },
        { kind: 'checkbox', ourField: 'opening_protection', whenValue: 'N', page: 4, x: 37.51, y: 598.41, size: 4.5 },
        { kind: 'checkbox', ourField: 'opening_protection_non_glazed_level', whenValue: 'N.1', page: 4, x: 85.51, y: 563.97, size: 4.5 },
        { kind: 'checkbox', ourField: 'opening_protection_non_glazed_level', whenValue: 'N.2', page: 4, x: 85.51, y: 552.45, size: 4.5 },
        { kind: 'checkbox', ourField: 'opening_protection_non_glazed_level', whenValue: 'N.3', page: 4, x: 85.51, y: 530.61, size: 4.5 },
        { kind: 'checkbox', ourField: 'opening_protection', whenValue: 'X', page: 4, x: 37.51, y: 508.77, size: 4.5 },
        { kind: 'checkbox', ourField: 'opening_protection', whenValue: 'Z', page: 4, x: 37.51, y: 474.33, size: 4.5 },
        { kind: 'checkbox', ourField: 'opening_protection_chart_windows_or_entry_doors', whenValue: 'NA', page: 3, x: 299.18, y: 604.03, size: 8.0 },
        { kind: 'checkbox', ourField: 'opening_protection_chart_garage_doors_glazed', whenValue: 'NA', page: 3, x: 348.78, y: 604.03, size: 8.0 },
        { kind: 'checkbox', ourField: 'opening_protection_chart_skylights', whenValue: 'NA', page: 3, x: 403.68, y: 604.03, size: 8.0 },
        { kind: 'checkbox', ourField: 'opening_protection_chart_glass_block', whenValue: 'NA', page: 3, x: 455.63, y: 604.03, size: 8.0 },
        { kind: 'checkbox', ourField: 'opening_protection_chart_entry_doors_non_glazed', whenValue: 'NA', page: 3, x: 508.83, y: 604.03, size: 8.0 },
        { kind: 'checkbox', ourField: 'opening_protection_chart_garage_doors_non_glazed', whenValue: 'NA', page: 3, x: 558.73, y: 604.03, size: 8.0 },
        { kind: 'checkbox', ourField: 'opening_protection_chart_windows_or_entry_doors', whenValue: 'A', page: 3, x: 299.18, y: 578.18, size: 8.0 },
        { kind: 'checkbox', ourField: 'opening_protection_chart_garage_doors_glazed', whenValue: 'A', page: 3, x: 348.78, y: 578.18, size: 8.0 },
        { kind: 'checkbox', ourField: 'opening_protection_chart_skylights', whenValue: 'A', page: 3, x: 403.68, y: 578.18, size: 8.0 },
        { kind: 'checkbox', ourField: 'opening_protection_chart_glass_block', whenValue: 'A', page: 3, x: 455.63, y: 578.18, size: 8.0 },
        { kind: 'checkbox', ourField: 'opening_protection_chart_entry_doors_non_glazed', whenValue: 'A', page: 3, x: 508.83, y: 578.18, size: 8.0 },
        { kind: 'checkbox', ourField: 'opening_protection_chart_garage_doors_non_glazed', whenValue: 'A', page: 3, x: 558.73, y: 578.18, size: 8.0 },
        { kind: 'checkbox', ourField: 'opening_protection_chart_windows_or_entry_doors', whenValue: 'B', page: 3, x: 299.18, y: 553.38, size: 8.0 },
        { kind: 'checkbox', ourField: 'opening_protection_chart_garage_doors_glazed', whenValue: 'B', page: 3, x: 348.78, y: 553.38, size: 8.0 },
        { kind: 'checkbox', ourField: 'opening_protection_chart_skylights', whenValue: 'B', page: 3, x: 403.68, y: 553.38, size: 8.0 },
        { kind: 'checkbox', ourField: 'opening_protection_chart_glass_block', whenValue: 'B', page: 3, x: 455.63, y: 553.38, size: 8.0 },
        { kind: 'checkbox', ourField: 'opening_protection_chart_entry_doors_non_glazed', whenValue: 'B', page: 3, x: 508.83, y: 553.38, size: 8.0 },
        { kind: 'checkbox', ourField: 'opening_protection_chart_garage_doors_non_glazed', whenValue: 'B', page: 3, x: 558.73, y: 553.38, size: 8.0 },
        { kind: 'checkbox', ourField: 'opening_protection_chart_windows_or_entry_doors', whenValue: 'C', page: 3, x: 299.18, y: 529.48, size: 8.0 },
        { kind: 'checkbox', ourField: 'opening_protection_chart_garage_doors_glazed', whenValue: 'C', page: 3, x: 348.78, y: 529.48, size: 8.0 },
        { kind: 'checkbox', ourField: 'opening_protection_chart_skylights', whenValue: 'C', page: 3, x: 403.68, y: 529.48, size: 8.0 },
        { kind: 'checkbox', ourField: 'opening_protection_chart_glass_block', whenValue: 'C', page: 3, x: 455.63, y: 529.48, size: 8.0 },
        { kind: 'checkbox', ourField: 'opening_protection_chart_entry_doors_non_glazed', whenValue: 'C', page: 3, x: 508.83, y: 529.48, size: 8.0 },
        { kind: 'checkbox', ourField: 'opening_protection_chart_garage_doors_non_glazed', whenValue: 'C', page: 3, x: 558.73, y: 529.48, size: 8.0 },
        { kind: 'checkbox', ourField: 'opening_protection_chart_entry_doors_non_glazed', whenValue: 'D', page: 3, x: 508.83, y: 503.73, size: 8.0 },
        { kind: 'checkbox', ourField: 'opening_protection_chart_garage_doors_non_glazed', whenValue: 'D', page: 3, x: 558.73, y: 503.73, size: 8.0 },
        { kind: 'checkbox', ourField: 'opening_protection_chart_windows_or_entry_doors', whenValue: 'N_appears_a_or_b_unverified', page: 3, x: 299.18, y: 480.33, size: 8.0 },
        { kind: 'checkbox', ourField: 'opening_protection_chart_garage_doors_glazed', whenValue: 'N_appears_a_or_b_unverified', page: 3, x: 348.78, y: 480.33, size: 8.0 },
        { kind: 'checkbox', ourField: 'opening_protection_chart_skylights', whenValue: 'N_appears_a_or_b_unverified', page: 3, x: 403.68, y: 480.33, size: 8.0 },
        { kind: 'checkbox', ourField: 'opening_protection_chart_glass_block', whenValue: 'N_appears_a_or_b_unverified', page: 3, x: 455.63, y: 480.33, size: 8.0 },
        { kind: 'checkbox', ourField: 'opening_protection_chart_entry_doors_non_glazed', whenValue: 'N_appears_a_or_b_unverified', page: 3, x: 508.83, y: 480.33, size: 8.0 },
        { kind: 'checkbox', ourField: 'opening_protection_chart_garage_doors_non_glazed', whenValue: 'N_appears_a_or_b_unverified', page: 3, x: 558.73, y: 480.33, size: 8.0 },
        { kind: 'checkbox', ourField: 'opening_protection_chart_windows_or_entry_doors', whenValue: 'N_cannot_be_identified', page: 3, x: 299.18, y: 461.38, size: 8.0 },
        { kind: 'checkbox', ourField: 'opening_protection_chart_garage_doors_glazed', whenValue: 'N_cannot_be_identified', page: 3, x: 348.78, y: 461.38, size: 8.0 },
        { kind: 'checkbox', ourField: 'opening_protection_chart_skylights', whenValue: 'N_cannot_be_identified', page: 3, x: 403.68, y: 461.38, size: 8.0 },
        { kind: 'checkbox', ourField: 'opening_protection_chart_glass_block', whenValue: 'N_cannot_be_identified', page: 3, x: 455.63, y: 461.38, size: 8.0 },
        { kind: 'checkbox', ourField: 'opening_protection_chart_entry_doors_non_glazed', whenValue: 'N_cannot_be_identified', page: 3, x: 508.83, y: 461.38, size: 8.0 },
        { kind: 'checkbox', ourField: 'opening_protection_chart_garage_doors_non_glazed', whenValue: 'N_cannot_be_identified', page: 3, x: 558.73, y: 461.38, size: 8.0 },
        { kind: 'checkbox', ourField: 'opening_protection_chart_windows_or_entry_doors', whenValue: 'X', page: 3, x: 299.18, y: 441.83, size: 8.0 },
        { kind: 'checkbox', ourField: 'opening_protection_chart_garage_doors_glazed', whenValue: 'X', page: 3, x: 348.78, y: 441.83, size: 8.0 },
        { kind: 'checkbox', ourField: 'opening_protection_chart_skylights', whenValue: 'X', page: 3, x: 403.68, y: 441.83, size: 8.0 },
        { kind: 'checkbox', ourField: 'opening_protection_chart_glass_block', whenValue: 'X', page: 3, x: 455.63, y: 441.83, size: 8.0 },
        { kind: 'checkbox', ourField: 'opening_protection_chart_entry_doors_non_glazed', whenValue: 'X', page: 3, x: 508.83, y: 441.83, size: 8.0 },
        { kind: 'checkbox', ourField: 'opening_protection_chart_garage_doors_non_glazed', whenValue: 'X', page: 3, x: 558.73, y: 441.83, size: 8.0 },
        { kind: 'checkbox', ourField: 'opening_protection_chart_windows_or_entry_doors', whenValue: 'Z', page: 3, x: 299.18, y: 420.63, size: 8.0 },
        { kind: 'checkbox', ourField: 'opening_protection_chart_garage_doors_glazed', whenValue: 'Z', page: 3, x: 348.78, y: 420.63, size: 8.0 },
        { kind: 'checkbox', ourField: 'opening_protection_chart_skylights', whenValue: 'Z', page: 3, x: 403.68, y: 420.63, size: 8.0 },
        { kind: 'checkbox', ourField: 'opening_protection_chart_glass_block', whenValue: 'Z', page: 3, x: 455.63, y: 420.63, size: 8.0 },
        { kind: 'checkbox', ourField: 'opening_protection_chart_entry_doors_non_glazed', whenValue: 'Z', page: 3, x: 508.83, y: 420.63, size: 8.0 },
        { kind: 'checkbox', ourField: 'opening_protection_chart_garage_doors_non_glazed', whenValue: 'Z', page: 3, x: 558.73, y: 420.63, size: 8.0 },
        { kind: 'overlay', ourField: 'inspector_name', page: 4, x: 44.0, y: 395.55, size: 9.0, maxWidth: 168.0, maxHeight: 11.0 },
        { kind: 'overlay', ourField: 'inspector_license_type', page: 4, x: 222.0, y: 395.55, size: 9.0, maxWidth: 169.9, maxHeight: 11.0 },
        { kind: 'overlay', ourField: 'inspector_license_number', page: 4, x: 401.0, y: 395.55, size: 9.0, maxWidth: 170.8, maxHeight: 11.0 },
        { kind: 'overlay', ourField: 'inspection_company', page: 4, x: 44.0, y: 376.55, size: 9.0, maxWidth: 168.0, maxHeight: 11.0 },
        { kind: 'overlay', ourField: 'inspector_phone', page: 4, x: 401.0, y: 376.55, size: 9.0, maxWidth: 170.8, maxHeight: 11.0 },
        { kind: 'checkbox', ourField: 'inspector_qualification', whenValue: 'home_inspector', page: 4, x: 37.51, y: 336.57, size: 4.5 },
        { kind: 'checkbox', ourField: 'inspector_qualification', whenValue: 'building_code_inspector', page: 4, x: 37.51, y: 314.73, size: 4.5 },
        { kind: 'checkbox', ourField: 'inspector_qualification', whenValue: 'contractor', page: 4, x: 37.51, y: 303.21, size: 4.5 },
        { kind: 'checkbox', ourField: 'inspector_qualification', whenValue: 'professional_engineer', page: 4, x: 37.51, y: 291.69, size: 4.5 },
        { kind: 'checkbox', ourField: 'inspector_qualification', whenValue: 'professional_architect', page: 4, x: 37.51, y: 280.29, size: 4.5 },
        { kind: 'checkbox', ourField: 'inspector_qualification', whenValue: 'other_recognized_by_insurer', page: 4, x: 37.51, y: 268.77, size: 4.5 },
        { kind: 'overlay', ourField: 'inspector_printed_name', page: 5, x: 50.94, y: 656.44, size: 10.0, maxWidth: 129.1, maxHeight: 12.0 },
        { kind: 'overlay', ourField: 'employee_printed_name', page: 5, x: 314.46, y: 633.39, size: 10.0, maxWidth: 104.1, maxHeight: 12.0 },
        { kind: 'overlay', ourField: 'inspector_signature', page: 5, x: 171.4, y: 593.18, size: 10.0, maxWidth: 174.0, maxHeight: 12.0 },
        { kind: 'overlay', ourField: 'inspector_signature_date', page: 5, x: 374.68, y: 593.18, size: 10.0, maxWidth: 109.0, maxHeight: 12.0 },
        { kind: 'overlay', ourField: 'homeowner_signature', page: 5, x: 90.65, y: 448.84, size: 10.0, maxWidth: 207.9, maxHeight: 12.0 },
        { kind: 'overlay', ourField: 'homeowner_signature_date', page: 5, x: 330.77, y: 448.84, size: 10.0, maxWidth: 81.4, maxHeight: 12.0 },
    ],
};
