/**
 * Texas TREC REI 7-6 — the published revision and the map checked against it.
 *
 * -- GENERATED FROM THE SIGNED CANDIDATE, NOT TYPED BY HAND ------------------
 * The 245 mappings below were emitted from the artifact a person signed
 * (`checkedBy: Nathan`, 2026-08-29) rather than copied. Hand-copying would
 * introduce differences the signature does not cover, and this file exists to
 * carry that signature into the software unchanged.
 *
 * -- WHICH PDF THIS IS ------------------------------------------------------
 * The FILLABLE download, not the flat one. Both print the same 164 checkboxes,
 * but the fillable carries 81 text widgets against the flat's 17, and 81 of
 * these mappings address a widget by name. Rendering the map onto the other
 * file would not fail loudly -- the names simply would not resolve.
 *
 * -- THE HASH IS WRITTEN TWICE, ON PURPOSE ----------------------------------
 * Once on the revision and once on the map. A shared constant would make them
 * impossible to diverge -- and would also make that impossible to CHECK:
 * `check-statutory-fidelity.mjs` reads sha256 literals, and a constant it
 * cannot resolve reads to it as a file declaring none. A guard that cannot see
 * the thing it guards is worse than the typo it was meant to catch.
 *
 * -- THE DATES ARE THE AUTHORITY'S OWN --------------------------------------
 * TREC's own notice: the REI 7-6 "can be used by real estate inspectors on a
 * voluntary basis as of September 1, 2021, but is required for all real estate
 * inspections performed in Texas as of February 1, 2022."
 *
 * ⚠️ NOTHING DECLARES THIS FORM YET. Publishing the revision and its map is the
 * authority-document half. The other half is a template whose items feed these
 * 122 field names through a `statutoryForm` declaration, and no template
 * carries one. Until one does, `available: false` is the correct and only
 * answer any workspace gets.
 */
import type { StatutoryFormVersion } from '../form-registry';
import type { FieldMap } from '../field-map';

export const version: StatutoryFormVersion = {
    formId: 'tx_trec_rei',
    // The Commission's own title for the promulgated form, as the form prints it.
    formTitle: 'Texas Real Estate Commission Property Inspection Report',
    version: 'REI 7-6',
    // Voluntary from 2021-09-01, required from 2022-02-01 -- TREC's own wording.
    effectiveFrom: Date.UTC(2021, 8, 1),
    mandatoryFrom: Date.UTC(2022, 1, 1),
    // Still current: TREC has published no successor as of the publish date.
    effectiveUntil: null,
    withdrawn: null,
    sourceUrl: 'https://www.trec.texas.gov/sites/default/files/pdf-forms/REI%207-6_fillable.pdf',
    sourceHash: '5def4efc765aee953a028446596dd97b9f974cb0851153e15b07447568d3ed4c',
    publishedBy: 'InspectorHub',
    publishedAt: Date.UTC(2026, 7, 29),
};

export const fieldMap: FieldMap = {
    formId: 'tx_trec_rei',
    version: 'REI 7-6',
    sourceHash: '5def4efc765aee953a028446596dd97b9f974cb0851153e15b07447568d3ed4c',
    checkedBy: 'Nathan',
    checkedAt: Date.UTC(2026, 7, 29),
    requiredFields: [
        'client_name',
        'inspection_date',
        'property_address',
        'inspector_name',
        'inspector_license_number',
    ],
    mappings: [
        { kind: 'acroform', ourField: 'client_name', pdfField: 'Name of Client' },
        { kind: 'acroform', ourField: 'inspection_date', pdfField: 'Date of Inspection' },
        { kind: 'acroform', ourField: 'property_address', pdfField: 'Address of Inspected Property' },
        { kind: 'acroform', ourField: 'inspector_name', pdfField: 'Name of Inspector' },
        { kind: 'acroform', ourField: 'inspector_license_number', pdfField: 'TREC License' },
        { kind: 'acroform', ourField: 'sponsor_name', pdfField: 'Name of Sponsor if applicable' },
        { kind: 'acroform', ourField: 'sponsor_license_number', pdfField: 'TREC License_2' },
        { kind: 'acroform', ourField: 'additional_information_provided_by_inspector', pdfField: 'Text1' },
        { kind: 'acroform', ourField: 'page_total_on_page_2', pdfField: 'Page 2 of' },
        { kind: 'acroform', ourField: 'report_identification_on_page_3', pdfField: 'topmostSubform[0].Page3[0].TextField1[0]' },
        { kind: 'acroform', ourField: 'structural_foundations_foundation_type', pdfField: 'Text3' },
        { kind: 'acroform', ourField: 'structural_foundations_comments', pdfField: 'Text4' },
        { kind: 'acroform', ourField: 'structural_grading_and_drainage_comments', pdfField: 'Text5' },
        { kind: 'acroform', ourField: 'structural_roof_covering_materials_covering_type', pdfField: 'Text6' },
        { kind: 'acroform', ourField: 'structural_roof_covering_materials_viewed_from', pdfField: 'Text7' },
        { kind: 'acroform', ourField: 'structural_roof_covering_materials_comments', pdfField: 'Text8' },
        { kind: 'acroform', ourField: 'structural_roof_structures_and_attics_viewed_from', pdfField: 'Text9' },
        { kind: 'acroform', ourField: 'structural_roof_structures_and_attics_insulation_depth', pdfField: 'Text10' },
        { kind: 'acroform', ourField: 'structural_roof_structures_and_attics_comments', pdfField: 'Text11' },
        { kind: 'acroform', ourField: 'structural_walls_comments', pdfField: 'Text12' },
        { kind: 'acroform', ourField: 'structural_ceilings_and_floors_comments', pdfField: 'Text13' },
        { kind: 'acroform', ourField: 'structural_doors_comments', pdfField: 'Text14' },
        { kind: 'acroform', ourField: 'structural_windows_comments', pdfField: 'Text15' },
        { kind: 'acroform', ourField: 'structural_stairways_comments', pdfField: 'Text16' },
        { kind: 'acroform', ourField: 'structural_fireplaces_and_chimneys_comments', pdfField: 'Text17' },
        { kind: 'acroform', ourField: 'structural_porches_balconies_decks_carports_comments', pdfField: 'Text18' },
        { kind: 'acroform', ourField: 'structural_other_comments', pdfField: 'Text19' },
        { kind: 'acroform', ourField: 'page_total_on_page_3', pdfField: 'topmostSubform[0].Page3[0].TextField2[0]' },
        { kind: 'acroform', ourField: 'report_identification_on_page_4', pdfField: 'topmostSubform[0].Page4[0].TextField1[0]' },
        { kind: 'acroform', ourField: 'electrical_service_entrance_and_panels_comments', pdfField: 'Text20' },
        { kind: 'acroform', ourField: 'electrical_branch_circuits_devices_fixtures_wiring_type', pdfField: 'Text21' },
        { kind: 'acroform', ourField: 'electrical_branch_circuits_devices_fixtures_comments', pdfField: 'Tex22' },
        { kind: 'acroform', ourField: 'electrical_other_comments', pdfField: 'Text23' },
        { kind: 'acroform', ourField: 'hvac_heating_equipment_system_type', pdfField: 'Text24' },
        { kind: 'acroform', ourField: 'hvac_heating_equipment_energy_sources', pdfField: 'Text25' },
        { kind: 'acroform', ourField: 'hvac_heating_equipment_comments', pdfField: 'Text26' },
        { kind: 'acroform', ourField: 'hvac_cooling_equipment_system_type', pdfField: 'Text27' },
        { kind: 'acroform', ourField: 'hvac_cooling_equipment_comments', pdfField: 'Text28' },
        { kind: 'acroform', ourField: 'hvac_duct_systems_chases_vents_comments', pdfField: 'Text29' },
        { kind: 'acroform', ourField: 'hvac_other_comments', pdfField: 'Text30' },
        { kind: 'acroform', ourField: 'plumbing_supply_water_meter_location', pdfField: 'Text31' },
        { kind: 'acroform', ourField: 'plumbing_supply_main_water_supply_valve_location', pdfField: 'Text32' },
        { kind: 'acroform', ourField: 'plumbing_supply_static_water_pressure', pdfField: 'Text33' },
        { kind: 'acroform', ourField: 'plumbing_supply_piping_material', pdfField: 'Text34' },
        { kind: 'acroform', ourField: 'plumbing_supply_distribution_fixtures_comments', pdfField: 'Text35' },
        { kind: 'acroform', ourField: 'plumbing_drains_piping_material', pdfField: 'Text36' },
        { kind: 'acroform', ourField: 'plumbing_drains_wastes_vents_comments', pdfField: 'Text37' },
        { kind: 'acroform', ourField: 'plumbing_water_heating_equipment_energy_sources', pdfField: 'Text38' },
        { kind: 'acroform', ourField: 'plumbing_water_heating_equipment_capacity', pdfField: 'Text39' },
        { kind: 'acroform', ourField: 'plumbing_water_heating_equipment_comments', pdfField: 'Text40' },
        { kind: 'acroform', ourField: 'page_total_on_page_4', pdfField: 'topmostSubform[0].Page4[0].TextField2[0]' },
        { kind: 'acroform', ourField: 'report_identification_on_page_5', pdfField: 'topmostSubform[0].Page5[0].TextField1[0]' },
        { kind: 'acroform', ourField: 'plumbing_hydro_massage_therapy_equipment_comments', pdfField: 'Text41' },
        { kind: 'acroform', ourField: 'plumbing_gas_meter_location', pdfField: 'Text42' },
        { kind: 'acroform', ourField: 'plumbing_gas_distribution_piping_material', pdfField: 'Text43' },
        { kind: 'acroform', ourField: 'plumbing_gas_distribution_and_appliances_comments', pdfField: 'Text44' },
        { kind: 'acroform', ourField: 'plumbing_other_comments', pdfField: 'Text45' },
        { kind: 'acroform', ourField: 'appliances_dishwashers_comments', pdfField: 'Text46' },
        { kind: 'acroform', ourField: 'appliances_food_waste_disposers_comments', pdfField: 'Text47' },
        { kind: 'acroform', ourField: 'appliances_range_hood_and_exhaust_systems_comments', pdfField: 'Text48' },
        { kind: 'acroform', ourField: 'appliances_ranges_cooktops_ovens_comments', pdfField: 'Text49' },
        { kind: 'acroform', ourField: 'appliances_microwave_ovens_comments', pdfField: 'Text50' },
        { kind: 'acroform', ourField: 'appliances_mechanical_exhaust_vents_and_bathroom_heaters_comments', pdfField: 'Text51' },
        { kind: 'acroform', ourField: 'appliances_garage_door_operators_comments', pdfField: 'Text52' },
        { kind: 'acroform', ourField: 'appliances_dryer_exhaust_systems_comments', pdfField: 'Text53' },
        { kind: 'acroform', ourField: 'appliances_other_comments', pdfField: 'Text54' },
        { kind: 'acroform', ourField: 'page_total_on_page_5', pdfField: 'topmostSubform[0].Page5[0].TextField2[0]' },
        { kind: 'acroform', ourField: 'report_identification_on_page_6', pdfField: 'topmostSubform[0].Page6[0].TextField1[0]' },
        { kind: 'acroform', ourField: 'optional_landscape_irrigation_systems_comments', pdfField: 'Text55' },
        { kind: 'acroform', ourField: 'optional_swimming_pools_spas_hot_tubs_construction_type', pdfField: 'Text56' },
        { kind: 'acroform', ourField: 'optional_swimming_pools_spas_hot_tubs_comments', pdfField: 'Text57' },
        { kind: 'acroform', ourField: 'optional_outbuildings_comments', pdfField: 'Text58' },
        { kind: 'acroform', ourField: 'optional_private_water_wells_pump_type', pdfField: 'Text59' },
        { kind: 'acroform', ourField: 'optional_private_water_wells_storage_equipment_type', pdfField: 'Text60' },
        { kind: 'acroform', ourField: 'optional_private_water_wells_comments', pdfField: 'Text61' },
        { kind: 'acroform', ourField: 'optional_private_sewage_disposal_systems_system_type', pdfField: 'Text62' },
        { kind: 'acroform', ourField: 'optional_private_sewage_disposal_systems_drain_field_location', pdfField: 'Text63' },
        { kind: 'acroform', ourField: 'optional_private_sewage_disposal_systems_comments', pdfField: 'Text64' },
        { kind: 'acroform', ourField: 'optional_other_built_in_appliances_comments', pdfField: 'Text65' },
        { kind: 'acroform', ourField: 'optional_other_comments', pdfField: 'Text66' },
        { kind: 'acroform', ourField: 'page_total_on_page_6', pdfField: 'topmostSubform[0].Page6[0].TextField2[0]' },
        { kind: 'checkbox', ourField: 'structural_foundations_rating', whenValue: 'inspected', page: 2, x: 35.4, y: 654.5, size: 9.0 },
        { kind: 'checkbox', ourField: 'structural_foundations_rating', whenValue: 'not_inspected', page: 2, x: 53.3, y: 654.5, size: 9.0 },
        { kind: 'checkbox', ourField: 'structural_foundations_rating', whenValue: 'not_present', page: 2, x: 74.0, y: 654.5, size: 9.0 },
        { kind: 'checkbox', ourField: 'structural_foundations_rating', whenValue: 'deficient', page: 2, x: 92.6, y: 654.5, size: 9.0 },
        { kind: 'checkbox', ourField: 'structural_grading_and_drainage_rating', whenValue: 'inspected', page: 2, x: 35.4, y: 599.4, size: 9.0 },
        { kind: 'checkbox', ourField: 'structural_grading_and_drainage_rating', whenValue: 'not_inspected', page: 2, x: 53.3, y: 599.4, size: 9.0 },
        { kind: 'checkbox', ourField: 'structural_grading_and_drainage_rating', whenValue: 'not_present', page: 2, x: 74.0, y: 599.4, size: 9.0 },
        { kind: 'checkbox', ourField: 'structural_grading_and_drainage_rating', whenValue: 'deficient', page: 2, x: 92.6, y: 599.4, size: 9.0 },
        { kind: 'checkbox', ourField: 'structural_roof_covering_materials_rating', whenValue: 'inspected', page: 2, x: 35.4, y: 554.8, size: 9.0 },
        { kind: 'checkbox', ourField: 'structural_roof_covering_materials_rating', whenValue: 'not_inspected', page: 2, x: 53.3, y: 554.8, size: 9.0 },
        { kind: 'checkbox', ourField: 'structural_roof_covering_materials_rating', whenValue: 'not_present', page: 2, x: 74.0, y: 554.8, size: 9.0 },
        { kind: 'checkbox', ourField: 'structural_roof_covering_materials_rating', whenValue: 'deficient', page: 2, x: 92.6, y: 554.8, size: 9.0 },
        { kind: 'checkbox', ourField: 'structural_roof_structures_and_attics_rating', whenValue: 'inspected', page: 2, x: 35.4, y: 487.7, size: 9.0 },
        { kind: 'checkbox', ourField: 'structural_roof_structures_and_attics_rating', whenValue: 'not_inspected', page: 2, x: 53.3, y: 487.7, size: 9.0 },
        { kind: 'checkbox', ourField: 'structural_roof_structures_and_attics_rating', whenValue: 'not_present', page: 2, x: 74.0, y: 487.7, size: 9.0 },
        { kind: 'checkbox', ourField: 'structural_roof_structures_and_attics_rating', whenValue: 'deficient', page: 2, x: 92.6, y: 487.7, size: 9.0 },
        { kind: 'checkbox', ourField: 'structural_walls_rating', whenValue: 'inspected', page: 2, x: 36.1, y: 420.0, size: 9.0 },
        { kind: 'checkbox', ourField: 'structural_walls_rating', whenValue: 'not_inspected', page: 2, x: 54.0, y: 420.0, size: 9.0 },
        { kind: 'checkbox', ourField: 'structural_walls_rating', whenValue: 'not_present', page: 2, x: 74.6, y: 420.0, size: 9.0 },
        { kind: 'checkbox', ourField: 'structural_walls_rating', whenValue: 'deficient', page: 2, x: 93.2, y: 420.0, size: 9.0 },
        { kind: 'checkbox', ourField: 'structural_ceilings_and_floors_rating', whenValue: 'inspected', page: 2, x: 35.4, y: 375.4, size: 9.0 },
        { kind: 'checkbox', ourField: 'structural_ceilings_and_floors_rating', whenValue: 'not_inspected', page: 2, x: 53.3, y: 375.4, size: 9.0 },
        { kind: 'checkbox', ourField: 'structural_ceilings_and_floors_rating', whenValue: 'not_present', page: 2, x: 74.0, y: 375.4, size: 9.0 },
        { kind: 'checkbox', ourField: 'structural_ceilings_and_floors_rating', whenValue: 'deficient', page: 2, x: 92.6, y: 375.4, size: 9.0 },
        { kind: 'checkbox', ourField: 'structural_doors_rating', whenValue: 'inspected', page: 2, x: 35.4, y: 330.9, size: 9.0 },
        { kind: 'checkbox', ourField: 'structural_doors_rating', whenValue: 'not_inspected', page: 2, x: 53.3, y: 330.9, size: 9.0 },
        { kind: 'checkbox', ourField: 'structural_doors_rating', whenValue: 'not_present', page: 2, x: 74.0, y: 330.9, size: 9.0 },
        { kind: 'checkbox', ourField: 'structural_doors_rating', whenValue: 'deficient', page: 2, x: 92.6, y: 330.9, size: 9.0 },
        { kind: 'checkbox', ourField: 'structural_windows_rating', whenValue: 'inspected', page: 2, x: 35.4, y: 287.0, size: 9.0 },
        { kind: 'checkbox', ourField: 'structural_windows_rating', whenValue: 'not_inspected', page: 2, x: 53.3, y: 287.0, size: 9.0 },
        { kind: 'checkbox', ourField: 'structural_windows_rating', whenValue: 'not_present', page: 2, x: 74.0, y: 287.0, size: 9.0 },
        { kind: 'checkbox', ourField: 'structural_windows_rating', whenValue: 'deficient', page: 2, x: 92.6, y: 287.0, size: 9.0 },
        { kind: 'checkbox', ourField: 'structural_stairways_rating', whenValue: 'inspected', page: 2, x: 36.7, y: 242.5, size: 9.0 },
        { kind: 'checkbox', ourField: 'structural_stairways_rating', whenValue: 'not_inspected', page: 2, x: 54.7, y: 242.5, size: 9.0 },
        { kind: 'checkbox', ourField: 'structural_stairways_rating', whenValue: 'not_present', page: 2, x: 75.3, y: 242.5, size: 9.0 },
        { kind: 'checkbox', ourField: 'structural_stairways_rating', whenValue: 'deficient', page: 2, x: 93.9, y: 242.5, size: 9.0 },
        { kind: 'checkbox', ourField: 'structural_fireplaces_and_chimneys_rating', whenValue: 'inspected', page: 2, x: 35.4, y: 198.7, size: 9.0 },
        { kind: 'checkbox', ourField: 'structural_fireplaces_and_chimneys_rating', whenValue: 'not_inspected', page: 2, x: 53.3, y: 198.7, size: 9.0 },
        { kind: 'checkbox', ourField: 'structural_fireplaces_and_chimneys_rating', whenValue: 'not_present', page: 2, x: 74.0, y: 198.7, size: 9.0 },
        { kind: 'checkbox', ourField: 'structural_fireplaces_and_chimneys_rating', whenValue: 'deficient', page: 2, x: 92.6, y: 198.7, size: 9.0 },
        { kind: 'checkbox', ourField: 'structural_porches_balconies_decks_carports_rating', whenValue: 'inspected', page: 2, x: 36.1, y: 154.2, size: 9.0 },
        { kind: 'checkbox', ourField: 'structural_porches_balconies_decks_carports_rating', whenValue: 'not_inspected', page: 2, x: 54.0, y: 154.2, size: 9.0 },
        { kind: 'checkbox', ourField: 'structural_porches_balconies_decks_carports_rating', whenValue: 'not_present', page: 2, x: 74.6, y: 154.2, size: 9.0 },
        { kind: 'checkbox', ourField: 'structural_porches_balconies_decks_carports_rating', whenValue: 'deficient', page: 2, x: 93.2, y: 154.2, size: 9.0 },
        { kind: 'checkbox', ourField: 'structural_other_rating', whenValue: 'inspected', page: 2, x: 36.1, y: 109.6, size: 9.0 },
        { kind: 'checkbox', ourField: 'structural_other_rating', whenValue: 'not_inspected', page: 2, x: 54.0, y: 109.6, size: 9.0 },
        { kind: 'checkbox', ourField: 'structural_other_rating', whenValue: 'not_present', page: 2, x: 74.6, y: 109.6, size: 9.0 },
        { kind: 'checkbox', ourField: 'structural_other_rating', whenValue: 'deficient', page: 2, x: 93.2, y: 109.6, size: 9.0 },
        { kind: 'checkbox', ourField: 'electrical_service_entrance_and_panels_rating', whenValue: 'inspected', page: 3, x: 36.1, y: 661.5, size: 9.0 },
        { kind: 'checkbox', ourField: 'electrical_service_entrance_and_panels_rating', whenValue: 'not_inspected', page: 3, x: 54.0, y: 661.5, size: 9.0 },
        { kind: 'checkbox', ourField: 'electrical_service_entrance_and_panels_rating', whenValue: 'not_present', page: 3, x: 74.6, y: 661.5, size: 9.0 },
        { kind: 'checkbox', ourField: 'electrical_service_entrance_and_panels_rating', whenValue: 'deficient', page: 3, x: 93.2, y: 661.5, size: 9.0 },
        { kind: 'checkbox', ourField: 'electrical_branch_circuits_devices_fixtures_rating', whenValue: 'inspected', page: 3, x: 36.1, y: 617.0, size: 9.0 },
        { kind: 'checkbox', ourField: 'electrical_branch_circuits_devices_fixtures_rating', whenValue: 'not_inspected', page: 3, x: 54.0, y: 617.0, size: 9.0 },
        { kind: 'checkbox', ourField: 'electrical_branch_circuits_devices_fixtures_rating', whenValue: 'not_present', page: 3, x: 74.6, y: 617.0, size: 9.0 },
        { kind: 'checkbox', ourField: 'electrical_branch_circuits_devices_fixtures_rating', whenValue: 'deficient', page: 3, x: 93.2, y: 617.0, size: 9.0 },
        { kind: 'checkbox', ourField: 'electrical_other_rating', whenValue: 'inspected', page: 3, x: 36.1, y: 558.6, size: 9.0 },
        { kind: 'checkbox', ourField: 'electrical_other_rating', whenValue: 'not_inspected', page: 3, x: 54.0, y: 558.6, size: 9.0 },
        { kind: 'checkbox', ourField: 'electrical_other_rating', whenValue: 'not_present', page: 3, x: 74.6, y: 558.6, size: 9.0 },
        { kind: 'checkbox', ourField: 'electrical_other_rating', whenValue: 'deficient', page: 3, x: 93.2, y: 558.6, size: 9.0 },
        { kind: 'checkbox', ourField: 'hvac_heating_equipment_rating', whenValue: 'inspected', page: 3, x: 35.4, y: 494.8, size: 9.0 },
        { kind: 'checkbox', ourField: 'hvac_heating_equipment_rating', whenValue: 'not_inspected', page: 3, x: 53.3, y: 494.8, size: 9.0 },
        { kind: 'checkbox', ourField: 'hvac_heating_equipment_rating', whenValue: 'not_present', page: 3, x: 74.0, y: 494.8, size: 9.0 },
        { kind: 'checkbox', ourField: 'hvac_heating_equipment_rating', whenValue: 'deficient', page: 3, x: 92.6, y: 494.8, size: 9.0 },
        { kind: 'checkbox', ourField: 'hvac_cooling_equipment_rating', whenValue: 'inspected', page: 3, x: 35.1, y: 427.0, size: 9.0 },
        { kind: 'checkbox', ourField: 'hvac_cooling_equipment_rating', whenValue: 'not_inspected', page: 3, x: 53.0, y: 427.0, size: 9.0 },
        { kind: 'checkbox', ourField: 'hvac_cooling_equipment_rating', whenValue: 'not_present', page: 3, x: 73.6, y: 427.0, size: 9.0 },
        { kind: 'checkbox', ourField: 'hvac_cooling_equipment_rating', whenValue: 'deficient', page: 3, x: 92.2, y: 427.0, size: 9.0 },
        { kind: 'checkbox', ourField: 'hvac_duct_systems_chases_vents_rating', whenValue: 'inspected', page: 3, x: 36.1, y: 371.5, size: 9.0 },
        { kind: 'checkbox', ourField: 'hvac_duct_systems_chases_vents_rating', whenValue: 'not_inspected', page: 3, x: 54.0, y: 371.5, size: 9.0 },
        { kind: 'checkbox', ourField: 'hvac_duct_systems_chases_vents_rating', whenValue: 'not_present', page: 3, x: 74.6, y: 371.5, size: 9.0 },
        { kind: 'checkbox', ourField: 'hvac_duct_systems_chases_vents_rating', whenValue: 'deficient', page: 3, x: 93.2, y: 371.5, size: 9.0 },
        { kind: 'checkbox', ourField: 'hvac_other_rating', whenValue: 'inspected', page: 3, x: 36.1, y: 324.5, size: 9.0 },
        { kind: 'checkbox', ourField: 'hvac_other_rating', whenValue: 'not_inspected', page: 3, x: 54.0, y: 324.5, size: 9.0 },
        { kind: 'checkbox', ourField: 'hvac_other_rating', whenValue: 'not_present', page: 3, x: 74.6, y: 324.5, size: 9.0 },
        { kind: 'checkbox', ourField: 'hvac_other_rating', whenValue: 'deficient', page: 3, x: 93.2, y: 324.5, size: 9.0 },
        { kind: 'checkbox', ourField: 'plumbing_supply_distribution_fixtures_rating', whenValue: 'inspected', page: 3, x: 36.1, y: 262.6, size: 9.0 },
        { kind: 'checkbox', ourField: 'plumbing_supply_distribution_fixtures_rating', whenValue: 'not_inspected', page: 3, x: 54.0, y: 262.6, size: 9.0 },
        { kind: 'checkbox', ourField: 'plumbing_supply_distribution_fixtures_rating', whenValue: 'not_present', page: 3, x: 74.6, y: 262.6, size: 9.0 },
        { kind: 'checkbox', ourField: 'plumbing_supply_distribution_fixtures_rating', whenValue: 'deficient', page: 3, x: 93.2, y: 262.6, size: 9.0 },
        { kind: 'checkbox', ourField: 'plumbing_drains_wastes_vents_rating', whenValue: 'inspected', page: 3, x: 36.1, y: 171.5, size: 9.0 },
        { kind: 'checkbox', ourField: 'plumbing_drains_wastes_vents_rating', whenValue: 'not_inspected', page: 3, x: 54.0, y: 171.5, size: 9.0 },
        { kind: 'checkbox', ourField: 'plumbing_drains_wastes_vents_rating', whenValue: 'not_present', page: 3, x: 74.6, y: 171.5, size: 9.0 },
        { kind: 'checkbox', ourField: 'plumbing_drains_wastes_vents_rating', whenValue: 'deficient', page: 3, x: 93.2, y: 171.5, size: 9.0 },
        { kind: 'checkbox', ourField: 'plumbing_water_heating_equipment_rating', whenValue: 'inspected', page: 3, x: 36.1, y: 116.0, size: 9.0 },
        { kind: 'checkbox', ourField: 'plumbing_water_heating_equipment_rating', whenValue: 'not_inspected', page: 3, x: 54.0, y: 116.0, size: 9.0 },
        { kind: 'checkbox', ourField: 'plumbing_water_heating_equipment_rating', whenValue: 'not_present', page: 3, x: 74.6, y: 116.0, size: 9.0 },
        { kind: 'checkbox', ourField: 'plumbing_water_heating_equipment_rating', whenValue: 'deficient', page: 3, x: 93.2, y: 116.0, size: 9.0 },
        { kind: 'checkbox', ourField: 'plumbing_hydro_massage_therapy_equipment_rating', whenValue: 'inspected', page: 4, x: 36.1, y: 674.2, size: 9.0 },
        { kind: 'checkbox', ourField: 'plumbing_hydro_massage_therapy_equipment_rating', whenValue: 'not_inspected', page: 4, x: 54.0, y: 674.2, size: 9.0 },
        { kind: 'checkbox', ourField: 'plumbing_hydro_massage_therapy_equipment_rating', whenValue: 'not_present', page: 4, x: 74.6, y: 674.2, size: 9.0 },
        { kind: 'checkbox', ourField: 'plumbing_hydro_massage_therapy_equipment_rating', whenValue: 'deficient', page: 4, x: 93.2, y: 674.2, size: 9.0 },
        { kind: 'checkbox', ourField: 'plumbing_gas_distribution_and_appliances_rating', whenValue: 'inspected', page: 4, x: 36.1, y: 625.0, size: 9.0 },
        { kind: 'checkbox', ourField: 'plumbing_gas_distribution_and_appliances_rating', whenValue: 'not_inspected', page: 4, x: 54.0, y: 625.0, size: 9.0 },
        { kind: 'checkbox', ourField: 'plumbing_gas_distribution_and_appliances_rating', whenValue: 'not_present', page: 4, x: 74.6, y: 625.0, size: 9.0 },
        { kind: 'checkbox', ourField: 'plumbing_gas_distribution_and_appliances_rating', whenValue: 'deficient', page: 4, x: 93.2, y: 625.0, size: 9.0 },
        { kind: 'checkbox', ourField: 'plumbing_other_rating', whenValue: 'inspected', page: 4, x: 35.4, y: 558.1, size: 9.0 },
        { kind: 'checkbox', ourField: 'plumbing_other_rating', whenValue: 'not_inspected', page: 4, x: 53.3, y: 558.1, size: 9.0 },
        { kind: 'checkbox', ourField: 'plumbing_other_rating', whenValue: 'not_present', page: 4, x: 74.0, y: 558.1, size: 9.0 },
        { kind: 'checkbox', ourField: 'plumbing_other_rating', whenValue: 'deficient', page: 4, x: 92.6, y: 558.1, size: 9.0 },
        { kind: 'checkbox', ourField: 'appliances_dishwashers_rating', whenValue: 'inspected', page: 4, x: 36.1, y: 495.1, size: 9.0 },
        { kind: 'checkbox', ourField: 'appliances_dishwashers_rating', whenValue: 'not_inspected', page: 4, x: 54.0, y: 495.1, size: 9.0 },
        { kind: 'checkbox', ourField: 'appliances_dishwashers_rating', whenValue: 'not_present', page: 4, x: 74.6, y: 495.1, size: 9.0 },
        { kind: 'checkbox', ourField: 'appliances_dishwashers_rating', whenValue: 'deficient', page: 4, x: 93.2, y: 495.1, size: 9.0 },
        { kind: 'checkbox', ourField: 'appliances_food_waste_disposers_rating', whenValue: 'inspected', page: 4, x: 35.4, y: 449.9, size: 9.0 },
        { kind: 'checkbox', ourField: 'appliances_food_waste_disposers_rating', whenValue: 'not_inspected', page: 4, x: 53.3, y: 449.9, size: 9.0 },
        { kind: 'checkbox', ourField: 'appliances_food_waste_disposers_rating', whenValue: 'not_present', page: 4, x: 74.0, y: 449.9, size: 9.0 },
        { kind: 'checkbox', ourField: 'appliances_food_waste_disposers_rating', whenValue: 'deficient', page: 4, x: 92.6, y: 449.9, size: 9.0 },
        { kind: 'checkbox', ourField: 'appliances_range_hood_and_exhaust_systems_rating', whenValue: 'inspected', page: 4, x: 35.1, y: 409.4, size: 9.0 },
        { kind: 'checkbox', ourField: 'appliances_range_hood_and_exhaust_systems_rating', whenValue: 'not_inspected', page: 4, x: 53.0, y: 409.4, size: 9.0 },
        { kind: 'checkbox', ourField: 'appliances_range_hood_and_exhaust_systems_rating', whenValue: 'not_present', page: 4, x: 73.6, y: 409.4, size: 9.0 },
        { kind: 'checkbox', ourField: 'appliances_range_hood_and_exhaust_systems_rating', whenValue: 'deficient', page: 4, x: 92.2, y: 409.4, size: 9.0 },
        { kind: 'checkbox', ourField: 'appliances_ranges_cooktops_ovens_rating', whenValue: 'inspected', page: 4, x: 35.1, y: 364.2, size: 9.0 },
        { kind: 'checkbox', ourField: 'appliances_ranges_cooktops_ovens_rating', whenValue: 'not_inspected', page: 4, x: 53.0, y: 364.2, size: 9.0 },
        { kind: 'checkbox', ourField: 'appliances_ranges_cooktops_ovens_rating', whenValue: 'not_present', page: 4, x: 73.6, y: 364.2, size: 9.0 },
        { kind: 'checkbox', ourField: 'appliances_ranges_cooktops_ovens_rating', whenValue: 'deficient', page: 4, x: 92.2, y: 364.2, size: 9.0 },
        { kind: 'checkbox', ourField: 'appliances_microwave_ovens_rating', whenValue: 'inspected', page: 4, x: 36.4, y: 320.4, size: 9.0 },
        { kind: 'checkbox', ourField: 'appliances_microwave_ovens_rating', whenValue: 'not_inspected', page: 4, x: 54.3, y: 320.4, size: 9.0 },
        { kind: 'checkbox', ourField: 'appliances_microwave_ovens_rating', whenValue: 'not_present', page: 4, x: 75.0, y: 320.4, size: 9.0 },
        { kind: 'checkbox', ourField: 'appliances_microwave_ovens_rating', whenValue: 'deficient', page: 4, x: 93.6, y: 320.4, size: 9.0 },
        { kind: 'checkbox', ourField: 'appliances_mechanical_exhaust_vents_and_bathroom_heaters_rating', whenValue: 'inspected', page: 4, x: 35.0, y: 277.0, size: 9.0 },
        { kind: 'checkbox', ourField: 'appliances_mechanical_exhaust_vents_and_bathroom_heaters_rating', whenValue: 'not_inspected', page: 4, x: 53.0, y: 277.0, size: 9.0 },
        { kind: 'checkbox', ourField: 'appliances_mechanical_exhaust_vents_and_bathroom_heaters_rating', whenValue: 'not_present', page: 4, x: 73.6, y: 277.0, size: 9.0 },
        { kind: 'checkbox', ourField: 'appliances_mechanical_exhaust_vents_and_bathroom_heaters_rating', whenValue: 'deficient', page: 4, x: 92.2, y: 277.0, size: 9.0 },
        { kind: 'checkbox', ourField: 'appliances_garage_door_operators_rating', whenValue: 'inspected', page: 4, x: 36.1, y: 231.5, size: 9.0 },
        { kind: 'checkbox', ourField: 'appliances_garage_door_operators_rating', whenValue: 'not_inspected', page: 4, x: 54.0, y: 231.5, size: 9.0 },
        { kind: 'checkbox', ourField: 'appliances_garage_door_operators_rating', whenValue: 'not_present', page: 4, x: 74.6, y: 231.5, size: 9.0 },
        { kind: 'checkbox', ourField: 'appliances_garage_door_operators_rating', whenValue: 'deficient', page: 4, x: 93.2, y: 231.5, size: 9.0 },
        { kind: 'checkbox', ourField: 'appliances_dryer_exhaust_systems_rating', whenValue: 'inspected', page: 4, x: 36.1, y: 187.0, size: 9.0 },
        { kind: 'checkbox', ourField: 'appliances_dryer_exhaust_systems_rating', whenValue: 'not_inspected', page: 4, x: 54.0, y: 187.0, size: 9.0 },
        { kind: 'checkbox', ourField: 'appliances_dryer_exhaust_systems_rating', whenValue: 'not_present', page: 4, x: 74.6, y: 187.0, size: 9.0 },
        { kind: 'checkbox', ourField: 'appliances_dryer_exhaust_systems_rating', whenValue: 'deficient', page: 4, x: 93.2, y: 187.0, size: 9.0 },
        { kind: 'checkbox', ourField: 'appliances_other_rating', whenValue: 'inspected', page: 4, x: 35.1, y: 143.2, size: 9.0 },
        { kind: 'checkbox', ourField: 'appliances_other_rating', whenValue: 'not_inspected', page: 4, x: 53.0, y: 143.2, size: 9.0 },
        { kind: 'checkbox', ourField: 'appliances_other_rating', whenValue: 'not_present', page: 4, x: 73.6, y: 143.2, size: 9.0 },
        { kind: 'checkbox', ourField: 'appliances_other_rating', whenValue: 'deficient', page: 4, x: 92.2, y: 143.2, size: 9.0 },
        { kind: 'checkbox', ourField: 'optional_landscape_irrigation_systems_rating', whenValue: 'inspected', page: 5, x: 35.3, y: 640.5, size: 9.0 },
        { kind: 'checkbox', ourField: 'optional_landscape_irrigation_systems_rating', whenValue: 'not_inspected', page: 5, x: 54.0, y: 640.5, size: 9.0 },
        { kind: 'checkbox', ourField: 'optional_landscape_irrigation_systems_rating', whenValue: 'not_present', page: 5, x: 74.6, y: 640.5, size: 9.0 },
        { kind: 'checkbox', ourField: 'optional_landscape_irrigation_systems_rating', whenValue: 'deficient', page: 5, x: 93.2, y: 640.5, size: 9.0 },
        { kind: 'checkbox', ourField: 'optional_swimming_pools_spas_hot_tubs_rating', whenValue: 'inspected', page: 5, x: 36.1, y: 594.8, size: 9.0 },
        { kind: 'checkbox', ourField: 'optional_swimming_pools_spas_hot_tubs_rating', whenValue: 'not_inspected', page: 5, x: 54.0, y: 594.8, size: 9.0 },
        { kind: 'checkbox', ourField: 'optional_swimming_pools_spas_hot_tubs_rating', whenValue: 'not_present', page: 5, x: 74.6, y: 594.8, size: 9.0 },
        { kind: 'checkbox', ourField: 'optional_swimming_pools_spas_hot_tubs_rating', whenValue: 'deficient', page: 5, x: 93.2, y: 594.8, size: 9.0 },
        { kind: 'checkbox', ourField: 'optional_outbuildings_rating', whenValue: 'inspected', page: 5, x: 36.1, y: 529.3, size: 9.0 },
        { kind: 'checkbox', ourField: 'optional_outbuildings_rating', whenValue: 'not_inspected', page: 5, x: 54.0, y: 529.3, size: 9.0 },
        { kind: 'checkbox', ourField: 'optional_outbuildings_rating', whenValue: 'not_present', page: 5, x: 74.6, y: 529.3, size: 9.0 },
        { kind: 'checkbox', ourField: 'optional_outbuildings_rating', whenValue: 'deficient', page: 5, x: 93.2, y: 529.3, size: 9.0 },
        { kind: 'checkbox', ourField: 'optional_private_water_wells_rating', whenValue: 'inspected', page: 5, x: 36.0, y: 478.3, size: 9.0 },
        { kind: 'checkbox', ourField: 'optional_private_water_wells_rating', whenValue: 'not_inspected', page: 5, x: 54.0, y: 478.3, size: 9.0 },
        { kind: 'checkbox', ourField: 'optional_private_water_wells_rating', whenValue: 'not_present', page: 5, x: 74.6, y: 478.3, size: 9.0 },
        { kind: 'checkbox', ourField: 'optional_private_water_wells_rating', whenValue: 'deficient', page: 5, x: 93.2, y: 478.3, size: 9.0 },
        { kind: 'checkbox', ourField: 'optional_private_sewage_disposal_systems_rating', whenValue: 'inspected', page: 5, x: 36.0, y: 406.3, size: 9.0 },
        { kind: 'checkbox', ourField: 'optional_private_sewage_disposal_systems_rating', whenValue: 'not_inspected', page: 5, x: 54.0, y: 406.3, size: 9.0 },
        { kind: 'checkbox', ourField: 'optional_private_sewage_disposal_systems_rating', whenValue: 'not_present', page: 5, x: 74.6, y: 406.3, size: 9.0 },
        { kind: 'checkbox', ourField: 'optional_private_sewage_disposal_systems_rating', whenValue: 'deficient', page: 5, x: 93.2, y: 406.3, size: 9.0 },
        { kind: 'checkbox', ourField: 'optional_other_built_in_appliances_rating', whenValue: 'inspected', page: 5, x: 36.0, y: 340.3, size: 9.0 },
        { kind: 'checkbox', ourField: 'optional_other_built_in_appliances_rating', whenValue: 'not_inspected', page: 5, x: 54.0, y: 340.3, size: 9.0 },
        { kind: 'checkbox', ourField: 'optional_other_built_in_appliances_rating', whenValue: 'not_present', page: 5, x: 74.6, y: 340.3, size: 9.0 },
        { kind: 'checkbox', ourField: 'optional_other_built_in_appliances_rating', whenValue: 'deficient', page: 5, x: 93.2, y: 340.3, size: 9.0 },
        { kind: 'checkbox', ourField: 'optional_other_rating', whenValue: 'inspected', page: 5, x: 36.0, y: 293.0, size: 9.0 },
        { kind: 'checkbox', ourField: 'optional_other_rating', whenValue: 'not_inspected', page: 5, x: 54.0, y: 293.0, size: 9.0 },
        { kind: 'checkbox', ourField: 'optional_other_rating', whenValue: 'not_present', page: 5, x: 74.6, y: 293.0, size: 9.0 },
        { kind: 'checkbox', ourField: 'optional_other_rating', whenValue: 'deficient', page: 5, x: 93.2, y: 293.0, size: 9.0 },
    ],
};
